/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.microedition.lcdui.ChoiceGroup
 *  javax.microedition.lcdui.Command
 *  javax.microedition.lcdui.CommandListener
 *  javax.microedition.lcdui.Display
 *  javax.microedition.lcdui.Displayable
 *  javax.microedition.lcdui.Form
 *  javax.microedition.lcdui.Item
 *  javax.microedition.midlet.MIDlet
 */
import javax.microedition.lcdui.ChoiceGroup;
import javax.microedition.lcdui.Command;
import javax.microedition.lcdui.CommandListener;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import javax.microedition.lcdui.Form;
import javax.microedition.lcdui.Item;
import javax.microedition.midlet.MIDlet;

public class cw
extends Form
implements CommandListener {
    private /* synthetic */ ChoiceGroup a;
    private /* synthetic */ Command b;
    private static final /* synthetic */ int[] lIlIlI;

    public cw() {
        byte[] byArray = new byte[lIlIlI[0]];
        byArray[cw.lIlIlI[1]] = lIlIlI[1];
        byArray[cw.lIlIlI[2]] = lIlIlI[3];
        byArray[cw.lIlIlI[4]] = lIlIlI[1];
        byArray[cw.lIlIlI[5]] = lIlIlI[6];
        byArray[cw.lIlIlI[7]] = lIlIlI[1];
        byArray[cw.lIlIlI[8]] = lIlIlI[9];
        byArray[cw.lIlIlI[10]] = lIlIlI[1];
        byArray[cw.lIlIlI[11]] = lIlIlI[12];
        byArray[cw.lIlIlI[13]] = lIlIlI[2];
        byArray[cw.lIlIlI[14]] = lIlIlI[15];
        byArray[cw.lIlIlI[16]] = lIlIlI[17];
        byArray[cw.lIlIlI[18]] = lIlIlI[19];
        byArray[cw.lIlIlI[20]] = lIlIlI[1];
        byArray[cw.lIlIlI[21]] = lIlIlI[22];
        byArray[cw.lIlIlI[23]] = lIlIlI[1];
        byArray[cw.lIlIlI[24]] = lIlIlI[12];
        byArray[cw.lIlIlI[25]] = lIlIlI[1];
        byArray[cw.lIlIlI[15]] = lIlIlI[26];
        byArray[cw.lIlIlI[27]] = lIlIlI[17];
        byArray[cw.lIlIlI[28]] = lIlIlI[29];
        byArray[cw.lIlIlI[30]] = lIlIlI[1];
        byArray[cw.lIlIlI[31]] = lIlIlI[32];
        byArray[cw.lIlIlI[33]] = lIlIlI[1];
        byArray[cw.lIlIlI[34]] = lIlIlI[12];
        byArray[cw.lIlIlI[35]] = lIlIlI[2];
        byArray[cw.lIlIlI[36]] = lIlIlI[15];
        byArray[cw.lIlIlI[37]] = lIlIlI[17];
        byArray[cw.lIlIlI[38]] = lIlIlI[39];
        super(ec.a(byArray));
        byte[] byArray2 = new byte[lIlIlI[20]];
        byArray2[cw.lIlIlI[1]] = lIlIlI[1];
        byArray2[cw.lIlIlI[2]] = lIlIlI[40];
        byArray2[cw.lIlIlI[4]] = lIlIlI[17];
        byArray2[cw.lIlIlI[5]] = lIlIlI[29];
        byArray2[cw.lIlIlI[7]] = lIlIlI[1];
        byArray2[cw.lIlIlI[8]] = lIlIlI[32];
        byArray2[cw.lIlIlI[10]] = lIlIlI[1];
        byArray2[cw.lIlIlI[11]] = lIlIlI[12];
        byArray2[cw.lIlIlI[13]] = lIlIlI[2];
        byArray2[cw.lIlIlI[14]] = lIlIlI[15];
        byArray2[cw.lIlIlI[16]] = lIlIlI[17];
        byArray2[cw.lIlIlI[18]] = lIlIlI[39];
        String[] stringArray = new String[lIlIlI[7]];
        byte[] byArray3 = new byte[lIlIlI[33]];
        byArray3[cw.lIlIlI[1]] = lIlIlI[1];
        byArray3[cw.lIlIlI[2]] = lIlIlI[41];
        byArray3[cw.lIlIlI[4]] = lIlIlI[17];
        byArray3[cw.lIlIlI[5]] = lIlIlI[42];
        byArray3[cw.lIlIlI[7]] = lIlIlI[1];
        byArray3[cw.lIlIlI[8]] = lIlIlI[22];
        byArray3[cw.lIlIlI[10]] = lIlIlI[1];
        byArray3[cw.lIlIlI[11]] = lIlIlI[12];
        byArray3[cw.lIlIlI[13]] = lIlIlI[1];
        byArray3[cw.lIlIlI[14]] = lIlIlI[22];
        byArray3[cw.lIlIlI[16]] = lIlIlI[17];
        byArray3[cw.lIlIlI[18]] = lIlIlI[43];
        byArray3[cw.lIlIlI[20]] = lIlIlI[1];
        byArray3[cw.lIlIlI[21]] = lIlIlI[9];
        byArray3[cw.lIlIlI[23]] = lIlIlI[1];
        byArray3[cw.lIlIlI[24]] = lIlIlI[12];
        byArray3[cw.lIlIlI[25]] = lIlIlI[1];
        byArray3[cw.lIlIlI[15]] = lIlIlI[32];
        byArray3[cw.lIlIlI[27]] = lIlIlI[1];
        byArray3[cw.lIlIlI[28]] = lIlIlI[44];
        byArray3[cw.lIlIlI[30]] = lIlIlI[17];
        byArray3[cw.lIlIlI[31]] = lIlIlI[45];
        stringArray[cw.lIlIlI[1]] = ec.a(byArray3);
        byte[] byArray4 = new byte[lIlIlI[46]];
        byArray4[cw.lIlIlI[1]] = lIlIlI[1];
        byArray4[cw.lIlIlI[2]] = lIlIlI[47];
        byArray4[cw.lIlIlI[4]] = lIlIlI[1];
        byArray4[cw.lIlIlI[5]] = lIlIlI[48];
        byArray4[cw.lIlIlI[7]] = lIlIlI[1];
        byArray4[cw.lIlIlI[8]] = lIlIlI[49];
        byArray4[cw.lIlIlI[10]] = lIlIlI[1];
        byArray4[cw.lIlIlI[11]] = lIlIlI[12];
        byArray4[cw.lIlIlI[13]] = lIlIlI[17];
        byArray4[cw.lIlIlI[14]] = lIlIlI[50];
        byArray4[cw.lIlIlI[16]] = lIlIlI[1];
        byArray4[cw.lIlIlI[18]] = lIlIlI[12];
        byArray4[cw.lIlIlI[20]] = lIlIlI[1];
        byArray4[cw.lIlIlI[21]] = lIlIlI[22];
        byArray4[cw.lIlIlI[23]] = lIlIlI[1];
        byArray4[cw.lIlIlI[24]] = lIlIlI[51];
        byArray4[cw.lIlIlI[25]] = lIlIlI[2];
        byArray4[cw.lIlIlI[15]] = lIlIlI[52];
        byArray4[cw.lIlIlI[27]] = lIlIlI[17];
        byArray4[cw.lIlIlI[28]] = lIlIlI[53];
        byArray4[cw.lIlIlI[30]] = lIlIlI[1];
        byArray4[cw.lIlIlI[31]] = lIlIlI[49];
        byArray4[cw.lIlIlI[33]] = lIlIlI[1];
        byArray4[cw.lIlIlI[34]] = lIlIlI[54];
        byArray4[cw.lIlIlI[35]] = lIlIlI[1];
        byArray4[cw.lIlIlI[36]] = lIlIlI[55];
        byArray4[cw.lIlIlI[37]] = lIlIlI[1];
        byArray4[cw.lIlIlI[38]] = lIlIlI[26];
        byArray4[cw.lIlIlI[0]] = lIlIlI[1];
        byArray4[cw.lIlIlI[56]] = lIlIlI[6];
        byArray4[cw.lIlIlI[17]] = lIlIlI[1];
        byArray4[cw.lIlIlI[57]] = lIlIlI[49];
        byArray4[cw.lIlIlI[12]] = lIlIlI[1];
        byArray4[cw.lIlIlI[58]] = lIlIlI[54];
        stringArray[cw.lIlIlI[2]] = ec.a(byArray4);
        byte[] byArray5 = new byte[lIlIlI[30]];
        byArray5[cw.lIlIlI[1]] = lIlIlI[1];
        byArray5[cw.lIlIlI[2]] = lIlIlI[59];
        byArray5[cw.lIlIlI[4]] = lIlIlI[17];
        byArray5[cw.lIlIlI[5]] = lIlIlI[60];
        byArray5[cw.lIlIlI[7]] = lIlIlI[1];
        byArray5[cw.lIlIlI[8]] = lIlIlI[22];
        byArray5[cw.lIlIlI[10]] = lIlIlI[1];
        byArray5[cw.lIlIlI[11]] = lIlIlI[12];
        byArray5[cw.lIlIlI[13]] = lIlIlI[1];
        byArray5[cw.lIlIlI[14]] = lIlIlI[26];
        byArray5[cw.lIlIlI[16]] = lIlIlI[17];
        byArray5[cw.lIlIlI[18]] = lIlIlI[29];
        byArray5[cw.lIlIlI[20]] = lIlIlI[1];
        byArray5[cw.lIlIlI[21]] = lIlIlI[32];
        byArray5[cw.lIlIlI[23]] = lIlIlI[1];
        byArray5[cw.lIlIlI[24]] = lIlIlI[12];
        byArray5[cw.lIlIlI[25]] = lIlIlI[2];
        byArray5[cw.lIlIlI[15]] = lIlIlI[15];
        byArray5[cw.lIlIlI[27]] = lIlIlI[17];
        byArray5[cw.lIlIlI[28]] = lIlIlI[39];
        stringArray[cw.lIlIlI[4]] = ec.a(byArray5);
        byte[] byArray6 = new byte[lIlIlI[61]];
        byArray6[cw.lIlIlI[1]] = lIlIlI[1];
        byArray6[cw.lIlIlI[2]] = lIlIlI[41];
        byArray6[cw.lIlIlI[4]] = lIlIlI[17];
        byArray6[cw.lIlIlI[5]] = lIlIlI[42];
        byArray6[cw.lIlIlI[7]] = lIlIlI[1];
        byArray6[cw.lIlIlI[8]] = lIlIlI[22];
        byArray6[cw.lIlIlI[10]] = lIlIlI[1];
        byArray6[cw.lIlIlI[11]] = lIlIlI[12];
        byArray6[cw.lIlIlI[13]] = lIlIlI[1];
        byArray6[cw.lIlIlI[14]] = lIlIlI[62];
        byArray6[cw.lIlIlI[16]] = lIlIlI[1];
        byArray6[cw.lIlIlI[18]] = lIlIlI[12];
        byArray6[cw.lIlIlI[20]] = lIlIlI[1];
        byArray6[cw.lIlIlI[21]] = lIlIlI[63];
        byArray6[cw.lIlIlI[23]] = lIlIlI[1];
        byArray6[cw.lIlIlI[24]] = lIlIlI[64];
        byArray6[cw.lIlIlI[25]] = lIlIlI[1];
        byArray6[cw.lIlIlI[15]] = lIlIlI[49];
        byArray6[cw.lIlIlI[27]] = lIlIlI[1];
        byArray6[cw.lIlIlI[28]] = lIlIlI[55];
        byArray6[cw.lIlIlI[30]] = lIlIlI[1];
        byArray6[cw.lIlIlI[31]] = lIlIlI[47];
        byArray6[cw.lIlIlI[33]] = lIlIlI[1];
        byArray6[cw.lIlIlI[34]] = lIlIlI[48];
        byArray6[cw.lIlIlI[35]] = lIlIlI[1];
        byArray6[cw.lIlIlI[36]] = lIlIlI[49];
        byArray6[cw.lIlIlI[37]] = lIlIlI[1];
        byArray6[cw.lIlIlI[38]] = lIlIlI[12];
        byArray6[cw.lIlIlI[0]] = lIlIlI[1];
        byArray6[cw.lIlIlI[56]] = lIlIlI[49];
        byArray6[cw.lIlIlI[17]] = lIlIlI[1];
        byArray6[cw.lIlIlI[57]] = lIlIlI[44];
        byArray6[cw.lIlIlI[12]] = lIlIlI[1];
        byArray6[cw.lIlIlI[58]] = lIlIlI[9];
        byArray6[cw.lIlIlI[46]] = lIlIlI[17];
        byArray6[cw.lIlIlI[65]] = lIlIlI[66];
        byArray6[cw.lIlIlI[67]] = lIlIlI[1];
        byArray6[cw.lIlIlI[68]] = lIlIlI[69];
        byArray6[cw.lIlIlI[70]] = lIlIlI[1];
        byArray6[cw.lIlIlI[71]] = lIlIlI[12];
        byArray6[cw.lIlIlI[72]] = lIlIlI[1];
        byArray6[cw.lIlIlI[73]] = lIlIlI[63];
        byArray6[cw.lIlIlI[74]] = lIlIlI[1];
        byArray6[cw.lIlIlI[75]] = lIlIlI[64];
        byArray6[cw.lIlIlI[76]] = lIlIlI[1];
        byArray6[cw.lIlIlI[77]] = lIlIlI[49];
        stringArray[cw.lIlIlI[5]] = ec.a(byArray6);
        this.a = new ChoiceGroup(ec.a(byArray2), lIlIlI[2], stringArray, null);
        this.append((Item)this.a);
        byte[] byArray7 = new byte[lIlIlI[10]];
        byArray7[cw.lIlIlI[1]] = lIlIlI[1];
        byArray7[cw.lIlIlI[2]] = lIlIlI[40];
        byArray7[cw.lIlIlI[4]] = lIlIlI[2];
        byArray7[cw.lIlIlI[5]] = lIlIlI[52];
        byArray7[cw.lIlIlI[7]] = lIlIlI[1];
        byArray7[cw.lIlIlI[8]] = lIlIlI[69];
        this.b = new Command(ec.a(byArray7), lIlIlI[7], lIlIlI[1]);
        this.addCommand(this.b);
        byte[] byArray8 = new byte[lIlIlI[16]];
        byArray8[cw.lIlIlI[1]] = lIlIlI[1];
        byArray8[cw.lIlIlI[2]] = lIlIlI[59];
        byArray8[cw.lIlIlI[4]] = lIlIlI[1];
        byArray8[cw.lIlIlI[5]] = lIlIlI[44];
        byArray8[cw.lIlIlI[7]] = lIlIlI[1];
        byArray8[cw.lIlIlI[8]] = lIlIlI[78];
        byArray8[cw.lIlIlI[10]] = lIlIlI[1];
        byArray8[cw.lIlIlI[11]] = lIlIlI[48];
        byArray8[cw.lIlIlI[13]] = lIlIlI[1];
        byArray8[cw.lIlIlI[14]] = lIlIlI[22];
        this.addCommand(new Command(ec.a(byArray8), lIlIlI[11], lIlIlI[1]));
        this.setCommandListener(this);
        this.a.setSelectedIndex(at.Q, lIlIlI[2]);
    }

    public static String a() {
        if (at.Q == 0) {
            byte[] byArray = new byte[lIlIlI[33]];
            byArray[cw.lIlIlI[1]] = lIlIlI[1];
            byArray[cw.lIlIlI[2]] = lIlIlI[41];
            byArray[cw.lIlIlI[4]] = lIlIlI[17];
            byArray[cw.lIlIlI[5]] = lIlIlI[42];
            byArray[cw.lIlIlI[7]] = lIlIlI[1];
            byArray[cw.lIlIlI[8]] = lIlIlI[22];
            byArray[cw.lIlIlI[10]] = lIlIlI[1];
            byArray[cw.lIlIlI[11]] = lIlIlI[12];
            byArray[cw.lIlIlI[13]] = lIlIlI[1];
            byArray[cw.lIlIlI[14]] = lIlIlI[22];
            byArray[cw.lIlIlI[16]] = lIlIlI[17];
            byArray[cw.lIlIlI[18]] = lIlIlI[43];
            byArray[cw.lIlIlI[20]] = lIlIlI[1];
            byArray[cw.lIlIlI[21]] = lIlIlI[9];
            byArray[cw.lIlIlI[23]] = lIlIlI[1];
            byArray[cw.lIlIlI[24]] = lIlIlI[12];
            byArray[cw.lIlIlI[25]] = lIlIlI[1];
            byArray[cw.lIlIlI[15]] = lIlIlI[32];
            byArray[cw.lIlIlI[27]] = lIlIlI[1];
            byArray[cw.lIlIlI[28]] = lIlIlI[44];
            byArray[cw.lIlIlI[30]] = lIlIlI[17];
            byArray[cw.lIlIlI[31]] = lIlIlI[45];
            return ec.a(byArray);
        }
        if (at.Q == lIlIlI[2]) {
            byte[] byArray = new byte[lIlIlI[46]];
            byArray[cw.lIlIlI[1]] = lIlIlI[1];
            byArray[cw.lIlIlI[2]] = lIlIlI[47];
            byArray[cw.lIlIlI[4]] = lIlIlI[1];
            byArray[cw.lIlIlI[5]] = lIlIlI[48];
            byArray[cw.lIlIlI[7]] = lIlIlI[1];
            byArray[cw.lIlIlI[8]] = lIlIlI[49];
            byArray[cw.lIlIlI[10]] = lIlIlI[1];
            byArray[cw.lIlIlI[11]] = lIlIlI[12];
            byArray[cw.lIlIlI[13]] = lIlIlI[17];
            byArray[cw.lIlIlI[14]] = lIlIlI[50];
            byArray[cw.lIlIlI[16]] = lIlIlI[1];
            byArray[cw.lIlIlI[18]] = lIlIlI[12];
            byArray[cw.lIlIlI[20]] = lIlIlI[1];
            byArray[cw.lIlIlI[21]] = lIlIlI[22];
            byArray[cw.lIlIlI[23]] = lIlIlI[1];
            byArray[cw.lIlIlI[24]] = lIlIlI[51];
            byArray[cw.lIlIlI[25]] = lIlIlI[2];
            byArray[cw.lIlIlI[15]] = lIlIlI[52];
            byArray[cw.lIlIlI[27]] = lIlIlI[17];
            byArray[cw.lIlIlI[28]] = lIlIlI[53];
            byArray[cw.lIlIlI[30]] = lIlIlI[1];
            byArray[cw.lIlIlI[31]] = lIlIlI[49];
            byArray[cw.lIlIlI[33]] = lIlIlI[1];
            byArray[cw.lIlIlI[34]] = lIlIlI[54];
            byArray[cw.lIlIlI[35]] = lIlIlI[1];
            byArray[cw.lIlIlI[36]] = lIlIlI[55];
            byArray[cw.lIlIlI[37]] = lIlIlI[1];
            byArray[cw.lIlIlI[38]] = lIlIlI[26];
            byArray[cw.lIlIlI[0]] = lIlIlI[1];
            byArray[cw.lIlIlI[56]] = lIlIlI[6];
            byArray[cw.lIlIlI[17]] = lIlIlI[1];
            byArray[cw.lIlIlI[57]] = lIlIlI[49];
            byArray[cw.lIlIlI[12]] = lIlIlI[1];
            byArray[cw.lIlIlI[58]] = lIlIlI[54];
            return ec.a(byArray);
        }
        if (at.Q == lIlIlI[5]) {
            byte[] byArray = new byte[lIlIlI[23]];
            byArray[cw.lIlIlI[1]] = lIlIlI[1];
            byArray[cw.lIlIlI[2]] = lIlIlI[40];
            byArray[cw.lIlIlI[4]] = lIlIlI[17];
            byArray[cw.lIlIlI[5]] = lIlIlI[29];
            byArray[cw.lIlIlI[7]] = lIlIlI[1];
            byArray[cw.lIlIlI[8]] = lIlIlI[32];
            byArray[cw.lIlIlI[10]] = lIlIlI[1];
            byArray[cw.lIlIlI[11]] = lIlIlI[12];
            byArray[cw.lIlIlI[13]] = lIlIlI[1];
            byArray[cw.lIlIlI[14]] = lIlIlI[79];
            byArray[cw.lIlIlI[16]] = lIlIlI[1];
            byArray[cw.lIlIlI[18]] = lIlIlI[9];
            byArray[cw.lIlIlI[20]] = lIlIlI[1];
            byArray[cw.lIlIlI[21]] = lIlIlI[80];
            return ec.a(byArray);
        }
        byte[] byArray = new byte[lIlIlI[10]];
        byArray[cw.lIlIlI[1]] = lIlIlI[1];
        byArray[cw.lIlIlI[2]] = lIlIlI[59];
        byArray[cw.lIlIlI[4]] = lIlIlI[17];
        byArray[cw.lIlIlI[5]] = lIlIlI[60];
        byArray[cw.lIlIlI[7]] = lIlIlI[1];
        byArray[cw.lIlIlI[8]] = lIlIlI[22];
        return ec.a(byArray);
    }

    public void commandAction(Command command, Displayable displayable) {
        if (this.b == command) {
            try {
                cw lllllIIIlIIIlIl;
                at.Q = lllllIIIlIIIlIl.a.getSelectedIndex();
                byte[] byArray = new byte[lIlIlI[27]];
                byArray[cw.lIlIlI[1]] = lIlIlI[1];
                byArray[cw.lIlIlI[2]] = lIlIlI[22];
                byArray[cw.lIlIlI[4]] = lIlIlI[1];
                byArray[cw.lIlIlI[5]] = lIlIlI[63];
                byArray[cw.lIlIlI[7]] = lIlIlI[1];
                byArray[cw.lIlIlI[8]] = lIlIlI[80];
                byArray[cw.lIlIlI[10]] = lIlIlI[1];
                byArray[cw.lIlIlI[11]] = lIlIlI[81];
                byArray[cw.lIlIlI[13]] = lIlIlI[1];
                byArray[cw.lIlIlI[14]] = lIlIlI[26];
                byArray[cw.lIlIlI[16]] = lIlIlI[1];
                byArray[cw.lIlIlI[18]] = lIlIlI[78];
                byArray[cw.lIlIlI[20]] = lIlIlI[1];
                byArray[cw.lIlIlI[21]] = lIlIlI[32];
                byArray[cw.lIlIlI[23]] = lIlIlI[1];
                byArray[cw.lIlIlI[24]] = lIlIlI[82];
                byArray[cw.lIlIlI[25]] = lIlIlI[1];
                byArray[cw.lIlIlI[15]] = lIlIlI[78];
                dv.a(ec.a(byArray), String.valueOf(at.Q));
                byte[] byArray2 = new byte[lIlIlI[76]];
                byArray2[cw.lIlIlI[1]] = lIlIlI[1];
                byArray2[cw.lIlIlI[2]] = lIlIlI[40];
                byArray2[cw.lIlIlI[4]] = lIlIlI[2];
                byArray2[cw.lIlIlI[5]] = lIlIlI[52];
                byArray2[cw.lIlIlI[7]] = lIlIlI[1];
                byArray2[cw.lIlIlI[8]] = lIlIlI[69];
                byArray2[cw.lIlIlI[10]] = lIlIlI[1];
                byArray2[cw.lIlIlI[11]] = lIlIlI[12];
                byArray2[cw.lIlIlI[13]] = lIlIlI[1];
                byArray2[cw.lIlIlI[14]] = lIlIlI[32];
                byArray2[cw.lIlIlI[16]] = lIlIlI[1];
                byArray2[cw.lIlIlI[18]] = lIlIlI[6];
                byArray2[cw.lIlIlI[20]] = lIlIlI[1];
                byArray2[cw.lIlIlI[21]] = lIlIlI[9];
                byArray2[cw.lIlIlI[23]] = lIlIlI[1];
                byArray2[cw.lIlIlI[24]] = lIlIlI[12];
                byArray2[cw.lIlIlI[25]] = lIlIlI[2];
                byArray2[cw.lIlIlI[15]] = lIlIlI[15];
                byArray2[cw.lIlIlI[27]] = lIlIlI[17];
                byArray2[cw.lIlIlI[28]] = lIlIlI[19];
                byArray2[cw.lIlIlI[30]] = lIlIlI[1];
                byArray2[cw.lIlIlI[31]] = lIlIlI[22];
                byArray2[cw.lIlIlI[33]] = lIlIlI[1];
                byArray2[cw.lIlIlI[34]] = lIlIlI[12];
                byArray2[cw.lIlIlI[35]] = lIlIlI[1];
                byArray2[cw.lIlIlI[36]] = lIlIlI[22];
                byArray2[cw.lIlIlI[37]] = lIlIlI[1];
                byArray2[cw.lIlIlI[38]] = lIlIlI[44];
                byArray2[cw.lIlIlI[0]] = lIlIlI[1];
                byArray2[cw.lIlIlI[56]] = lIlIlI[6];
                byArray2[cw.lIlIlI[17]] = lIlIlI[1];
                byArray2[cw.lIlIlI[57]] = lIlIlI[49];
                byArray2[cw.lIlIlI[12]] = lIlIlI[1];
                byArray2[cw.lIlIlI[58]] = lIlIlI[44];
                byArray2[cw.lIlIlI[46]] = lIlIlI[1];
                byArray2[cw.lIlIlI[65]] = lIlIlI[12];
                byArray2[cw.lIlIlI[67]] = lIlIlI[1];
                byArray2[cw.lIlIlI[68]] = lIlIlI[32];
                byArray2[cw.lIlIlI[70]] = lIlIlI[1];
                byArray2[cw.lIlIlI[71]] = lIlIlI[83];
                byArray2[cw.lIlIlI[72]] = lIlIlI[1];
                byArray2[cw.lIlIlI[73]] = lIlIlI[49];
                byArray2[cw.lIlIlI[74]] = lIlIlI[1];
                byArray2[cw.lIlIlI[75]] = lIlIlI[54];
                at.a(ec.a(byArray2));
            }
            catch (Exception exception) {
                // empty catch block
            }
        }
        Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)dc.a);
    }

    static {
        cw.llllI();
    }

    private static void llllI() {
        lIlIlI = new int[84];
        cw.lIlIlI[0] = (0x6A ^ 0x6D) << (" ".length() << " ".length());
        cw.lIlIlI[1] = (0xAE ^ 0xA5) << "   ".length() & ~((0x72 ^ 0x79) << "   ".length());
        cw.lIlIlI[2] = " ".length();
        cw.lIlIlI[3] = 0xE5 ^ 0xA6;
        cw.lIlIlI[4] = " ".length() << " ".length();
        cw.lIlIlI[5] = "   ".length();
        cw.lIlIlI[6] = -(0x12 ^ 0x32);
        cw.lIlIlI[7] = " ".length() << (" ".length() << " ".length());
        cw.lIlIlI[8] = 0x6E ^ 0x6B;
        cw.lIlIlI[9] = 0xC3 ^ 0xAA;
        cw.lIlIlI[10] = "   ".length() << " ".length();
        cw.lIlIlI[11] = 0x9F ^ 0x98;
        cw.lIlIlI[12] = " ".length() << (0x92 ^ 0x97);
        cw.lIlIlI[13] = " ".length() << "   ".length();
        cw.lIlIlI[14] = 0x33 ^ 0x3A;
        cw.lIlIlI[15] = 0xAA ^ 0xBB;
        cw.lIlIlI[16] = (0xA3 ^ 0xA6) << " ".length();
        cw.lIlIlI[17] = (0 ^ 0xF) << " ".length();
        cw.lIlIlI[18] = 0x45 ^ 0x4E;
        cw.lIlIlI[19] = -(0xE2 ^ 0xAB);
        cw.lIlIlI[20] = "   ".length() << (" ".length() << " ".length());
        cw.lIlIlI[21] = 0x28 ^ 0x25;
        cw.lIlIlI[22] = (0x4F ^ 0x52) << (" ".length() << " ".length());
        cw.lIlIlI[23] = (0x3E ^ 0x39) << " ".length();
        cw.lIlIlI[24] = 0xC9 ^ 0xC6;
        cw.lIlIlI[25] = " ".length() << (" ".length() << (" ".length() << " ".length()));
        cw.lIlIlI[26] = (0xB1 ^ 0xAA) << (" ".length() << " ".length());
        cw.lIlIlI[27] = (0x37 ^ 0x3E) << " ".length();
        cw.lIlIlI[28] = 0x78 ^ 0x6B;
        cw.lIlIlI[29] = -(0x80 ^ 0xB3);
        cw.lIlIlI[30] = (0x26 ^ 0x23) << (" ".length() << " ".length());
        cw.lIlIlI[31] = 0x3C ^ 0x29;
        cw.lIlIlI[32] = 0x52 ^ 0x31;
        cw.lIlIlI[33] = (0x56 ^ 0x5D) << " ".length();
        cw.lIlIlI[34] = 0xB9 ^ 0xAE;
        cw.lIlIlI[35] = "   ".length() << "   ".length();
        cw.lIlIlI[36] = 0xB3 ^ 0xAA;
        cw.lIlIlI[37] = (5 ^ 8) << " ".length();
        cw.lIlIlI[38] = 0x10 ^ 0xB;
        cw.lIlIlI[39] = -(0x72 ^ 0x5F);
        cw.lIlIlI[40] = (0x20 ^ 0x33) << (" ".length() << " ".length());
        cw.lIlIlI[41] = (0x27 ^ 0xC) << " ".length();
        cw.lIlIlI[42] = -(0x96 ^ 0x81);
        cw.lIlIlI[43] = -(0xF3 ^ 0xAC);
        cw.lIlIlI[44] = (0x16 ^ 0x1B) << "   ".length();
        cw.lIlIlI[45] = -(0x52 ^ 0x7B);
        cw.lIlIlI[46] = (0x3B ^ 0x2A) << " ".length();
        cw.lIlIlI[47] = (0x39 ^ 0x18) << " ".length();
        cw.lIlIlI[48] = -(0xB6 ^ 0xA9);
        cw.lIlIlI[49] = (0x38 ^ 0xF) << " ".length();
        cw.lIlIlI[50] = -(0xE5 ^ 0xC4);
        cw.lIlIlI[51] = (0x10 ^ 0x29) << " ".length();
        cw.lIlIlI[52] = -(0x61 ^ 0x31);
        cw.lIlIlI[53] = -(0x52 ^ 0x71);
        cw.lIlIlI[54] = 0x2B ^ 0x4C;
        cw.lIlIlI[55] = 0x4D ^ 0x62;
        cw.lIlIlI[56] = 0x92 ^ 0x8F;
        cw.lIlIlI[57] = 0xB9 ^ 0xA6;
        cw.lIlIlI[58] = 0x2C ^ 0xD;
        cw.lIlIlI[59] = (0xBD ^ 0xA8) << (" ".length() << " ".length());
        cw.lIlIlI[60] = -(0x94 ^ 0xC5);
        cw.lIlIlI[61] = (0x42 ^ 0x55) << " ".length();
        cw.lIlIlI[62] = 0xE ^ 0x3B;
        cw.lIlIlI[63] = 0x4A ^ 0x33;
        cw.lIlIlI[64] = -(0xAA ^ 0xBC);
        cw.lIlIlI[65] = 0x4F ^ 0x6C;
        cw.lIlIlI[66] = -(0x51 ^ 0x6E);
        cw.lIlIlI[67] = (0xCC ^ 0xC5) << (" ".length() << " ".length());
        cw.lIlIlI[68] = 0xAC ^ 0x89;
        cw.lIlIlI[69] = 0x26 ^ 0x53;
        cw.lIlIlI[70] = (0x6A ^ 0x79) << " ".length();
        cw.lIlIlI[71] = 0x11 ^ 0x36;
        cw.lIlIlI[72] = (0x18 ^ 0x1D) << "   ".length();
        cw.lIlIlI[73] = 0x49 ^ 0x60;
        cw.lIlIlI[74] = (0x1F ^ 0xA) << " ".length();
        cw.lIlIlI[75] = 0x45 ^ 0x6E;
        cw.lIlIlI[76] = (0x72 ^ 0x79) << (" ".length() << " ".length());
        cw.lIlIlI[77] = 0x72 ^ 0x5F;
        cw.lIlIlI[78] = 0x7C ^ 0x13;
        cw.lIlIlI[79] = (0xA6 ^ 0x9D) << " ".length();
        cw.lIlIlI[80] = (0x28 ^ 0x2F) << (" ".length() << (" ".length() << " ".length()));
        cw.lIlIlI[81] = 0xDB ^ 0xBE;
        cw.lIlIlI[82] = (0x15 ^ 0xC) << (" ".length() << " ".length());
        cw.lIlIlI[83] = -(0x3E ^ 0x32);
    }
}

