/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.microedition.lcdui.ChoiceGroup
 *  javax.microedition.lcdui.Command
 *  javax.microedition.lcdui.CommandListener
 *  javax.microedition.lcdui.Display
 *  javax.microedition.lcdui.Displayable
 *  javax.microedition.lcdui.Form
 *  javax.microedition.lcdui.Item
 *  javax.microedition.lcdui.TextField
 *  javax.microedition.midlet.MIDlet
 */
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.time.LocalTime;
import java.util.List;
import javax.microedition.lcdui.ChoiceGroup;
import javax.microedition.lcdui.Command;
import javax.microedition.lcdui.CommandListener;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import javax.microedition.lcdui.Form;
import javax.microedition.lcdui.Item;
import javax.microedition.lcdui.TextField;
import javax.microedition.midlet.MIDlet;

public class el
extends Form
implements CommandListener {
    private /* synthetic */ TextField f;
    private /* synthetic */ TextField g;
    public static /* synthetic */ String a;
    public static /* synthetic */ String b;
    public static /* synthetic */ boolean c;
    public static /* synthetic */ boolean d;
    public static /* synthetic */ boolean e;
    private /* synthetic */ ChoiceGroup h;
    private /* synthetic */ Command i;
    private static final /* synthetic */ int[] lIIIlIl;

    static {
        el.lllIII();
        byte[] byArray = new byte[lIIIlIl[0]];
        byArray[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray[el.lIIIlIl[2]] = lIIIlIl[3];
        byArray[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray[el.lIIIlIl[5]] = lIIIlIl[6];
        byArray[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray[el.lIIIlIl[8]] = lIIIlIl[9];
        byArray[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray[el.lIIIlIl[11]] = lIIIlIl[12];
        byArray[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray[el.lIIIlIl[14]] = lIIIlIl[15];
        byArray[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray[el.lIIIlIl[17]] = lIIIlIl[18];
        byArray[el.lIIIlIl[19]] = lIIIlIl[1];
        byArray[el.lIIIlIl[20]] = lIIIlIl[3];
        byArray[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray[el.lIIIlIl[22]] = lIIIlIl[6];
        byArray[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray[el.lIIIlIl[24]] = lIIIlIl[9];
        byArray[el.lIIIlIl[25]] = lIIIlIl[1];
        byArray[el.lIIIlIl[26]] = lIIIlIl[12];
        byArray[el.lIIIlIl[27]] = lIIIlIl[1];
        byArray[el.lIIIlIl[28]] = lIIIlIl[29];
        byArray[el.lIIIlIl[30]] = lIIIlIl[1];
        byArray[el.lIIIlIl[31]] = lIIIlIl[18];
        byArray[el.lIIIlIl[32]] = lIIIlIl[1];
        byArray[el.lIIIlIl[33]] = lIIIlIl[3];
        byArray[el.lIIIlIl[34]] = lIIIlIl[1];
        byArray[el.lIIIlIl[35]] = lIIIlIl[6];
        byArray[el.lIIIlIl[36]] = lIIIlIl[1];
        byArray[el.lIIIlIl[37]] = lIIIlIl[9];
        byArray[el.lIIIlIl[38]] = lIIIlIl[1];
        byArray[el.lIIIlIl[39]] = lIIIlIl[15];
        byArray[el.lIIIlIl[40]] = lIIIlIl[1];
        byArray[el.lIIIlIl[41]] = lIIIlIl[3];
        a = ec.a(byArray);
        byte[] byArray2 = new byte[lIIIlIl[0]];
        byArray2[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[2]] = lIIIlIl[3];
        byArray2[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[5]] = lIIIlIl[6];
        byArray2[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[8]] = lIIIlIl[9];
        byArray2[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[11]] = lIIIlIl[12];
        byArray2[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[14]] = lIIIlIl[12];
        byArray2[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[17]] = lIIIlIl[18];
        byArray2[el.lIIIlIl[19]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[20]] = lIIIlIl[3];
        byArray2[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[22]] = lIIIlIl[6];
        byArray2[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[24]] = lIIIlIl[9];
        byArray2[el.lIIIlIl[25]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[26]] = lIIIlIl[12];
        byArray2[el.lIIIlIl[27]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[28]] = lIIIlIl[42];
        byArray2[el.lIIIlIl[30]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[31]] = lIIIlIl[18];
        byArray2[el.lIIIlIl[32]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[33]] = lIIIlIl[3];
        byArray2[el.lIIIlIl[34]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[35]] = lIIIlIl[6];
        byArray2[el.lIIIlIl[36]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[37]] = lIIIlIl[9];
        byArray2[el.lIIIlIl[38]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[39]] = lIIIlIl[15];
        byArray2[el.lIIIlIl[40]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[41]] = lIIIlIl[43];
        b = ec.a(byArray2);
        c = lIIIlIl[1];
        d = lIIIlIl[1];
        e = lIIIlIl[1];
    }

    /*
     * WARNING - void declaration
     */
    static void a(List list, String string) {
        byte[] byArray = new byte[lIIIlIl[4]];
        byArray[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray[el.lIIIlIl[2]] = lIIIlIl[18];
        String[] stringArray = at.a(string, ec.a(byArray));
        int n2 = lIIIlIl[1];
        while (n2 < stringArray.length) {
            List llllIIIlIllllll;
            void llllIIIlIllllII;
            void llllIIIlIllllIl;
            byte[] byArray2 = new byte[lIIIlIl[4]];
            byArray2[el.lIIIlIl[1]] = lIIIlIl[1];
            byArray2[el.lIIIlIl[2]] = lIIIlIl[9];
            String[] llllIIIlIlllIll = at.a(llllIIIlIllllIl[llllIIIlIllllII].trim(), ec.a(byArray2));
            llllIIIlIllllll.add(LocalTime.of(Integer.parseInt(llllIIIlIlllIll[lIIIlIl[1]]), Integer.parseInt(llllIIIlIlllIll[lIIIlIl[2]])));
            ++llllIIIlIllllII;
        }
    }

    /*
     * WARNING - void declaration
     */
    static void a() {
        byte[] byArray = new byte[lIIIlIl[32]];
        byArray[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray[el.lIIIlIl[2]] = lIIIlIl[44];
        byArray[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray[el.lIIIlIl[5]] = lIIIlIl[45];
        byArray[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray[el.lIIIlIl[8]] = lIIIlIl[46];
        byArray[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray[el.lIIIlIl[11]] = lIIIlIl[46];
        byArray[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray[el.lIIIlIl[14]] = lIIIlIl[47];
        byArray[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray[el.lIIIlIl[17]] = lIIIlIl[48];
        byArray[el.lIIIlIl[19]] = lIIIlIl[1];
        byArray[el.lIIIlIl[20]] = lIIIlIl[49];
        byArray[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray[el.lIIIlIl[22]] = lIIIlIl[50];
        byArray[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray[el.lIIIlIl[24]] = lIIIlIl[48];
        byArray[el.lIIIlIl[25]] = lIIIlIl[1];
        byArray[el.lIIIlIl[26]] = lIIIlIl[50];
        byArray[el.lIIIlIl[27]] = lIIIlIl[1];
        byArray[el.lIIIlIl[28]] = lIIIlIl[51];
        byArray[el.lIIIlIl[30]] = lIIIlIl[1];
        byArray[el.lIIIlIl[31]] = lIIIlIl[51];
        byte[] byArray2 = dv.a(ec.a(byArray));
        if (byArray2 != null) {
            ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(byArray2);
            DataInputStream llllIIIlIllIlII = new DataInputStream(byteArrayInputStream);
            try {
                void llllIIIlIllIlIl;
                a = llllIIIlIllIlII.readUTF();
                b = llllIIIlIllIlII.readUTF();
                d = llllIIIlIllIlII.readBoolean();
                e = llllIIIlIllIlII.readBoolean();
                el.a(at.Y, a);
                el.a(at.Z, b);
                llllIIIlIllIlII.close();
                llllIIIlIllIlIl.close();
            }
            catch (Exception exception) {
                // empty catch block
            }
        }
    }

    public el(String string) {
        super(string);
        byte[] byArray = new byte[lIIIlIl[30]];
        byArray[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray[el.lIIIlIl[2]] = lIIIlIl[52];
        byArray[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray[el.lIIIlIl[5]] = lIIIlIl[53];
        byArray[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray[el.lIIIlIl[8]] = lIIIlIl[46];
        byArray[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray[el.lIIIlIl[11]] = lIIIlIl[54];
        byArray[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray[el.lIIIlIl[14]] = lIIIlIl[40];
        byArray[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray[el.lIIIlIl[17]] = lIIIlIl[50];
        byArray[el.lIIIlIl[19]] = lIIIlIl[1];
        byArray[el.lIIIlIl[20]] = lIIIlIl[48];
        byArray[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray[el.lIIIlIl[22]] = lIIIlIl[55];
        byArray[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray[el.lIIIlIl[24]] = lIIIlIl[50];
        byArray[el.lIIIlIl[25]] = lIIIlIl[1];
        byArray[el.lIIIlIl[26]] = lIIIlIl[51];
        byArray[el.lIIIlIl[27]] = lIIIlIl[1];
        byArray[el.lIIIlIl[28]] = lIIIlIl[51];
        String[] stringArray = new String[lIIIlIl[4]];
        byte[] byArray2 = new byte[lIIIlIl[27]];
        byArray2[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[2]] = lIIIlIl[56];
        byArray2[el.lIIIlIl[4]] = lIIIlIl[38];
        byArray2[el.lIIIlIl[5]] = lIIIlIl[57];
        byArray2[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[8]] = lIIIlIl[48];
        byArray2[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[11]] = lIIIlIl[40];
        byArray2[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[14]] = lIIIlIl[49];
        byArray2[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[17]] = lIIIlIl[47];
        byArray2[el.lIIIlIl[19]] = lIIIlIl[38];
        byArray2[el.lIIIlIl[20]] = lIIIlIl[58];
        byArray2[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[22]] = lIIIlIl[40];
        byArray2[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[24]] = lIIIlIl[50];
        byArray2[el.lIIIlIl[25]] = lIIIlIl[1];
        byArray2[el.lIIIlIl[26]] = lIIIlIl[59];
        stringArray[el.lIIIlIl[1]] = ec.a(byArray2);
        byte[] byArray3 = new byte[lIIIlIl[30]];
        byArray3[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[2]] = lIIIlIl[56];
        byArray3[el.lIIIlIl[4]] = lIIIlIl[38];
        byArray3[el.lIIIlIl[5]] = lIIIlIl[57];
        byArray3[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[8]] = lIIIlIl[48];
        byArray3[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[11]] = lIIIlIl[40];
        byArray3[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[14]] = lIIIlIl[49];
        byArray3[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[17]] = lIIIlIl[47];
        byArray3[el.lIIIlIl[19]] = lIIIlIl[38];
        byArray3[el.lIIIlIl[20]] = lIIIlIl[58];
        byArray3[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[22]] = lIIIlIl[40];
        byArray3[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[24]] = lIIIlIl[50];
        byArray3[el.lIIIlIl[25]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[26]] = lIIIlIl[60];
        byArray3[el.lIIIlIl[27]] = lIIIlIl[1];
        byArray3[el.lIIIlIl[28]] = lIIIlIl[60];
        stringArray[el.lIIIlIl[2]] = ec.a(byArray3);
        this.h = new ChoiceGroup(ec.a(byArray), lIIIlIl[4], stringArray, null);
        this.append((Item)this.h);
        byte[] byArray4 = new byte[lIIIlIl[61]];
        byArray4[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[2]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[5]] = lIIIlIl[62];
        byArray4[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[8]] = lIIIlIl[47];
        byArray4[el.lIIIlIl[10]] = lIIIlIl[38];
        byArray4[el.lIIIlIl[11]] = lIIIlIl[58];
        byArray4[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[14]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[17]] = lIIIlIl[50];
        byArray4[el.lIIIlIl[19]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[20]] = lIIIlIl[59];
        byArray4[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[22]] = lIIIlIl[63];
        byArray4[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[24]] = lIIIlIl[64];
        byArray4[el.lIIIlIl[25]] = lIIIlIl[38];
        byArray4[el.lIIIlIl[26]] = lIIIlIl[65];
        byArray4[el.lIIIlIl[27]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[28]] = lIIIlIl[47];
        byArray4[el.lIIIlIl[30]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[31]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[32]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[33]] = lIIIlIl[66];
        byArray4[el.lIIIlIl[34]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[35]] = lIIIlIl[67];
        byArray4[el.lIIIlIl[36]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[37]] = lIIIlIl[53];
        byArray4[el.lIIIlIl[38]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[39]] = lIIIlIl[48];
        byArray4[el.lIIIlIl[40]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[41]] = lIIIlIl[49];
        byArray4[el.lIIIlIl[0]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[68]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[69]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[70]] = lIIIlIl[49];
        byArray4[el.lIIIlIl[71]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[72]] = lIIIlIl[47];
        byArray4[el.lIIIlIl[63]] = lIIIlIl[38];
        byArray4[el.lIIIlIl[73]] = lIIIlIl[58];
        byArray4[el.lIIIlIl[74]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[75]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[18]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[76]] = lIIIlIl[77];
        byArray4[el.lIIIlIl[78]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[55]] = lIIIlIl[79];
        byArray4[el.lIIIlIl[43]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[3]] = lIIIlIl[77];
        byArray4[el.lIIIlIl[80]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[6]] = lIIIlIl[67];
        byArray4[el.lIIIlIl[12]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[15]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[81]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[42]] = lIIIlIl[48];
        byArray4[el.lIIIlIl[29]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[82]] = lIIIlIl[67];
        byArray4[el.lIIIlIl[9]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[83]] = lIIIlIl[84];
        byArray4[el.lIIIlIl[85]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[86]] = lIIIlIl[53];
        byArray4[el.lIIIlIl[87]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[88]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[89]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[52]] = lIIIlIl[90];
        byArray4[el.lIIIlIl[91]] = lIIIlIl[38];
        byArray4[el.lIIIlIl[92]] = lIIIlIl[93];
        byArray4[el.lIIIlIl[94]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[95]] = lIIIlIl[53];
        byArray4[el.lIIIlIl[60]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[62]] = lIIIlIl[40];
        byArray4[el.lIIIlIl[56]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[96]] = lIIIlIl[18];
        byArray4[el.lIIIlIl[97]] = lIIIlIl[1];
        byArray4[el.lIIIlIl[98]] = lIIIlIl[73];
        this.f = new TextField(ec.a(byArray4), String.valueOf(a), lIIIlIl[99], lIIIlIl[1]);
        this.append((Item)this.f);
        byte[] byArray5 = new byte[lIIIlIl[59]];
        byArray5[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[2]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[5]] = lIIIlIl[62];
        byArray5[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[8]] = lIIIlIl[47];
        byArray5[el.lIIIlIl[10]] = lIIIlIl[38];
        byArray5[el.lIIIlIl[11]] = lIIIlIl[58];
        byArray5[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[14]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[17]] = lIIIlIl[50];
        byArray5[el.lIIIlIl[19]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[20]] = lIIIlIl[60];
        byArray5[el.lIIIlIl[21]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[22]] = lIIIlIl[60];
        byArray5[el.lIIIlIl[23]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[24]] = lIIIlIl[63];
        byArray5[el.lIIIlIl[25]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[26]] = lIIIlIl[64];
        byArray5[el.lIIIlIl[27]] = lIIIlIl[38];
        byArray5[el.lIIIlIl[28]] = lIIIlIl[65];
        byArray5[el.lIIIlIl[30]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[31]] = lIIIlIl[47];
        byArray5[el.lIIIlIl[32]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[33]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[34]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[35]] = lIIIlIl[66];
        byArray5[el.lIIIlIl[36]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[37]] = lIIIlIl[67];
        byArray5[el.lIIIlIl[38]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[39]] = lIIIlIl[53];
        byArray5[el.lIIIlIl[40]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[41]] = lIIIlIl[48];
        byArray5[el.lIIIlIl[0]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[68]] = lIIIlIl[49];
        byArray5[el.lIIIlIl[69]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[70]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[71]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[72]] = lIIIlIl[49];
        byArray5[el.lIIIlIl[63]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[73]] = lIIIlIl[47];
        byArray5[el.lIIIlIl[74]] = lIIIlIl[38];
        byArray5[el.lIIIlIl[75]] = lIIIlIl[58];
        byArray5[el.lIIIlIl[18]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[76]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[78]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[55]] = lIIIlIl[77];
        byArray5[el.lIIIlIl[43]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[3]] = lIIIlIl[79];
        byArray5[el.lIIIlIl[80]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[6]] = lIIIlIl[77];
        byArray5[el.lIIIlIl[12]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[15]] = lIIIlIl[67];
        byArray5[el.lIIIlIl[81]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[42]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[29]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[82]] = lIIIlIl[48];
        byArray5[el.lIIIlIl[9]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[83]] = lIIIlIl[67];
        byArray5[el.lIIIlIl[85]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[86]] = lIIIlIl[84];
        byArray5[el.lIIIlIl[87]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[88]] = lIIIlIl[53];
        byArray5[el.lIIIlIl[89]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[52]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[91]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[92]] = lIIIlIl[90];
        byArray5[el.lIIIlIl[94]] = lIIIlIl[38];
        byArray5[el.lIIIlIl[95]] = lIIIlIl[93];
        byArray5[el.lIIIlIl[60]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[62]] = lIIIlIl[53];
        byArray5[el.lIIIlIl[56]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[96]] = lIIIlIl[40];
        byArray5[el.lIIIlIl[97]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[98]] = lIIIlIl[18];
        byArray5[el.lIIIlIl[61]] = lIIIlIl[1];
        byArray5[el.lIIIlIl[64]] = lIIIlIl[73];
        this.g = new TextField(ec.a(byArray5), String.valueOf(b), lIIIlIl[99], lIIIlIl[1]);
        this.append((Item)this.g);
        byte[] byArray6 = new byte[lIIIlIl[13]];
        byArray6[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray6[el.lIIIlIl[2]] = lIIIlIl[44];
        byArray6[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray6[el.lIIIlIl[5]] = lIIIlIl[84];
        byArray6[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray6[el.lIIIlIl[8]] = lIIIlIl[100];
        byArray6[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray6[el.lIIIlIl[11]] = lIIIlIl[45];
        this.i = new Command(ec.a(byArray6), lIIIlIl[7], lIIIlIl[1]);
        this.addCommand(this.i);
        byte[] byArray7 = new byte[lIIIlIl[19]];
        byArray7[el.lIIIlIl[1]] = lIIIlIl[1];
        byArray7[el.lIIIlIl[2]] = lIIIlIl[92];
        byArray7[el.lIIIlIl[4]] = lIIIlIl[1];
        byArray7[el.lIIIlIl[5]] = lIIIlIl[84];
        byArray7[el.lIIIlIl[7]] = lIIIlIl[1];
        byArray7[el.lIIIlIl[8]] = lIIIlIl[48];
        byArray7[el.lIIIlIl[10]] = lIIIlIl[1];
        byArray7[el.lIIIlIl[11]] = lIIIlIl[77];
        byArray7[el.lIIIlIl[13]] = lIIIlIl[1];
        byArray7[el.lIIIlIl[14]] = lIIIlIl[45];
        byArray7[el.lIIIlIl[16]] = lIIIlIl[1];
        byArray7[el.lIIIlIl[17]] = lIIIlIl[101];
        this.addCommand(new Command(ec.a(byArray7), lIIIlIl[11], lIIIlIl[1]));
        this.setCommandListener(this);
        this.h.setSelectedIndex(lIIIlIl[1], d);
        this.h.setSelectedIndex(lIIIlIl[2], e);
    }

    /*
     * WARNING - void declaration
     */
    public void commandAction(Command command, Displayable displayable) {
        if (command == this.i) {
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            DataOutputStream llllIIIlIlIlIlI = new DataOutputStream(byteArrayOutputStream);
            try {
                void llllIIIlIlIlIll;
                el llllIIIlIlIllIl;
                a = llllIIIlIlIllIl.f.getString();
                b = llllIIIlIlIllIl.g.getString();
                d = llllIIIlIlIllIl.h.isSelected(lIIIlIl[1]);
                e = llllIIIlIlIllIl.h.isSelected(lIIIlIl[2]);
                llllIIIlIlIlIlI.writeUTF(a);
                llllIIIlIlIlIlI.writeUTF(b);
                llllIIIlIlIlIlI.writeBoolean(d);
                llllIIIlIlIlIlI.writeBoolean(e);
                byte[] byArray = new byte[lIIIlIl[32]];
                byArray[el.lIIIlIl[1]] = lIIIlIl[1];
                byArray[el.lIIIlIl[2]] = lIIIlIl[44];
                byArray[el.lIIIlIl[4]] = lIIIlIl[1];
                byArray[el.lIIIlIl[5]] = lIIIlIl[45];
                byArray[el.lIIIlIl[7]] = lIIIlIl[1];
                byArray[el.lIIIlIl[8]] = lIIIlIl[46];
                byArray[el.lIIIlIl[10]] = lIIIlIl[1];
                byArray[el.lIIIlIl[11]] = lIIIlIl[46];
                byArray[el.lIIIlIl[13]] = lIIIlIl[1];
                byArray[el.lIIIlIl[14]] = lIIIlIl[47];
                byArray[el.lIIIlIl[16]] = lIIIlIl[1];
                byArray[el.lIIIlIl[17]] = lIIIlIl[48];
                byArray[el.lIIIlIl[19]] = lIIIlIl[1];
                byArray[el.lIIIlIl[20]] = lIIIlIl[49];
                byArray[el.lIIIlIl[21]] = lIIIlIl[1];
                byArray[el.lIIIlIl[22]] = lIIIlIl[50];
                byArray[el.lIIIlIl[23]] = lIIIlIl[1];
                byArray[el.lIIIlIl[24]] = lIIIlIl[48];
                byArray[el.lIIIlIl[25]] = lIIIlIl[1];
                byArray[el.lIIIlIl[26]] = lIIIlIl[50];
                byArray[el.lIIIlIl[27]] = lIIIlIl[1];
                byArray[el.lIIIlIl[28]] = lIIIlIl[51];
                byArray[el.lIIIlIl[30]] = lIIIlIl[1];
                byArray[el.lIIIlIl[31]] = lIIIlIl[51];
                dv.a(ec.a(byArray), ((ByteArrayOutputStream)llllIIIlIlIlIll).toByteArray());
                llllIIIlIlIlIlI.flush();
                llllIIIlIlIlIll.flush();
                byte[] byArray2 = new byte[lIIIlIl[18]];
                byArray2[el.lIIIlIl[1]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[2]] = lIIIlIl[61];
                byArray2[el.lIIIlIl[4]] = lIIIlIl[2];
                byArray2[el.lIIIlIl[5]] = lIIIlIl[102];
                byArray2[el.lIIIlIl[7]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[8]] = lIIIlIl[53];
                byArray2[el.lIIIlIl[10]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[11]] = lIIIlIl[40];
                byArray2[el.lIIIlIl[13]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[14]] = lIIIlIl[77];
                byArray2[el.lIIIlIl[16]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[17]] = lIIIlIl[103];
                byArray2[el.lIIIlIl[19]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[20]] = lIIIlIl[47];
                byArray2[el.lIIIlIl[21]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[22]] = lIIIlIl[40];
                byArray2[el.lIIIlIl[23]] = lIIIlIl[2];
                byArray2[el.lIIIlIl[24]] = lIIIlIl[24];
                byArray2[el.lIIIlIl[25]] = lIIIlIl[38];
                byArray2[el.lIIIlIl[26]] = lIIIlIl[104];
                byArray2[el.lIIIlIl[27]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[28]] = lIIIlIl[46];
                byArray2[el.lIIIlIl[30]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[31]] = lIIIlIl[40];
                byArray2[el.lIIIlIl[32]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[33]] = lIIIlIl[46];
                byArray2[el.lIIIlIl[34]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[35]] = lIIIlIl[67];
                byArray2[el.lIIIlIl[36]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[37]] = lIIIlIl[103];
                byArray2[el.lIIIlIl[38]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[39]] = lIIIlIl[48];
                byArray2[el.lIIIlIl[40]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[41]] = lIIIlIl[67];
                byArray2[el.lIIIlIl[0]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[68]] = lIIIlIl[40];
                byArray2[el.lIIIlIl[69]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[70]] = lIIIlIl[77];
                byArray2[el.lIIIlIl[71]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[72]] = lIIIlIl[105];
                byArray2[el.lIIIlIl[63]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[73]] = lIIIlIl[48];
                byArray2[el.lIIIlIl[74]] = lIIIlIl[1];
                byArray2[el.lIIIlIl[75]] = lIIIlIl[49];
                at.a(ec.a(byArray2));
                el.a(at.Y, a);
                el.a(at.Z, b);
            }
            catch (Exception llllIIIlIlIlIIl) {
                // empty catch block
            }
        }
        Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)dc.a);
    }

    private static void lllIII() {
        lIIIlIl = new int[106];
        el.lIIIlIl[0] = (0x71 ^ 0x60) << " ".length();
        el.lIIIlIl[1] = (0x11 ^ 0x44) & ~(0x5D ^ 8);
        el.lIIIlIl[2] = " ".length();
        el.lIIIlIl[3] = 0xF0 ^ 0xC1;
        el.lIIIlIl[4] = " ".length() << " ".length();
        el.lIIIlIl[5] = "   ".length();
        el.lIIIlIl[6] = 0x4C ^ 0x7F;
        el.lIIIlIl[7] = " ".length() << (" ".length() << " ".length());
        el.lIIIlIl[8] = 8 ^ 0xD;
        el.lIIIlIl[9] = (0x5B ^ 0x46) << " ".length();
        el.lIIIlIl[10] = "   ".length() << " ".length();
        el.lIIIlIl[11] = 0x63 ^ 0x64;
        el.lIIIlIl[12] = (0x4C ^ 0x41) << (" ".length() << " ".length());
        el.lIIIlIl[13] = " ".length() << "   ".length();
        el.lIIIlIl[14] = 0x11 ^ 0x18;
        el.lIIIlIl[15] = 0x52 ^ 0x67;
        el.lIIIlIl[16] = (0x73 ^ 0x76) << " ".length();
        el.lIIIlIl[17] = 0x86 ^ 0x8D;
        el.lIIIlIl[18] = (0x81 ^ 0x8A) << (" ".length() << " ".length());
        el.lIIIlIl[19] = "   ".length() << (" ".length() << " ".length());
        el.lIIIlIl[20] = 2 ^ 0xF;
        el.lIIIlIl[21] = (0x8A ^ 0x8D) << " ".length();
        el.lIIIlIl[22] = 0x6B ^ 0x64;
        el.lIIIlIl[23] = " ".length() << (" ".length() << (" ".length() << " ".length()));
        el.lIIIlIl[24] = 0x73 ^ 0x62;
        el.lIIIlIl[25] = (0xB7 ^ 0xBE) << " ".length();
        el.lIIIlIl[26] = 0x9F ^ 0x8C;
        el.lIIIlIl[27] = (0x6E ^ 0x6B) << (" ".length() << " ".length());
        el.lIIIlIl[28] = 0x2C ^ 0x39;
        el.lIIIlIl[29] = (0x6A ^ 0x6D) << "   ".length();
        el.lIIIlIl[30] = (0x3E ^ 0x35) << " ".length();
        el.lIIIlIl[31] = 0xD1 ^ 0xC6;
        el.lIIIlIl[32] = "   ".length() << "   ".length();
        el.lIIIlIl[33] = 0x4E ^ 0x57;
        el.lIIIlIl[34] = (0x6C ^ 0x61) << " ".length();
        el.lIIIlIl[35] = 0x67 ^ 0x7C;
        el.lIIIlIl[36] = (5 ^ 2) << (" ".length() << " ".length());
        el.lIIIlIl[37] = 0x33 ^ 0x2E;
        el.lIIIlIl[38] = (0x83 ^ 0x8C) << " ".length();
        el.lIIIlIl[39] = 0x27 ^ 0x38;
        el.lIIIlIl[40] = " ".length() << (0x76 ^ 0x73);
        el.lIIIlIl[41] = 0x6A ^ 0x4B;
        el.lIIIlIl[42] = 0x2E ^ 0x19;
        el.lIIIlIl[43] = "   ".length() << (" ".length() << (" ".length() << " ".length()));
        el.lIIIlIl[44] = 0x42 ^ 0x11;
        el.lIIIlIl[45] = 0x56 ^ 0x33;
        el.lIIIlIl[46] = (0xDB ^ 0xC6) << (" ".length() << " ".length());
        el.lIIIlIl[47] = 0xF1 ^ 0x98;
        el.lIIIlIl[48] = (0x94 ^ 0xA3) << " ".length();
        el.lIIIlIl[49] = 0x3C ^ 0x5B;
        el.lIIIlIl[50] = 0x52 ^ 0x1D;
        el.lIIIlIl[51] = (0x33 ^ 0) << " ".length();
        el.lIIIlIl[52] = 0x85 ^ 0xC4;
        el.lIIIlIl[53] = 0xCD ^ 0xB8;
        el.lIIIlIl[54] = 0x7B ^ 0x14;
        el.lIIIlIl[55] = 0x2E ^ 1;
        el.lIIIlIl[56] = (0x28 ^ 0x21) << "   ".length();
        el.lIIIlIl[57] = -(0xFD ^ 0xBA);
        el.lIIIlIl[58] = -(0xAF ^ 0x8C);
        el.lIIIlIl[59] = (0x1E ^ 0x39) << " ".length();
        el.lIIIlIl[60] = (0xE5 ^ 0xC6) << " ".length();
        el.lIIIlIl[61] = (0x97 ^ 0x84) << (" ".length() << " ".length());
        el.lIIIlIl[62] = 0xC8 ^ 0x8F;
        el.lIIIlIl[63] = (0x7D ^ 0x78) << "   ".length();
        el.lIIIlIl[64] = 0x1E ^ 0x53;
        el.lIIIlIl[65] = -(0x80 ^ 0xA9);
        el.lIIIlIl[66] = 0xC0 ^ 0xAB;
        el.lIIIlIl[67] = (0x7B ^ 0x76) << "   ".length();
        el.lIIIlIl[68] = 0xF ^ 0x2C;
        el.lIIIlIl[69] = (0x81 ^ 0x88) << (" ".length() << " ".length());
        el.lIIIlIl[70] = 0x58 ^ 0x7D;
        el.lIIIlIl[71] = (0x1C ^ 0xF) << " ".length();
        el.lIIIlIl[72] = 0x1D ^ 0x3A;
        el.lIIIlIl[73] = 0xB8 ^ 0x91;
        el.lIIIlIl[74] = (0x9D ^ 0x88) << " ".length();
        el.lIIIlIl[75] = 0xBB ^ 0x90;
        el.lIIIlIl[76] = 0x20 ^ 0xD;
        el.lIIIlIl[77] = 0xEC ^ 0x8F;
        el.lIIIlIl[78] = (0x82 ^ 0x95) << " ".length();
        el.lIIIlIl[79] = -(0x26 ^ 0x39);
        el.lIIIlIl[80] = (0x5A ^ 0x43) << " ".length();
        el.lIIIlIl[81] = (0x8E ^ 0x95) << " ".length();
        el.lIIIlIl[82] = 0x33 ^ 0xA;
        el.lIIIlIl[83] = 9 ^ 0x32;
        el.lIIIlIl[84] = 0xE6 ^ 0x87;
        el.lIIIlIl[85] = (0x94 ^ 0x9B) << (" ".length() << " ".length());
        el.lIIIlIl[86] = 3 ^ 0x3E;
        el.lIIIlIl[87] = (0x2F ^ 0x30) << " ".length();
        el.lIIIlIl[88] = 0x4A ^ 0x75;
        el.lIIIlIl[89] = " ".length() << ("   ".length() << " ".length());
        el.lIIIlIl[90] = (0xA6 ^ 0xBF) << (" ".length() << " ".length());
        el.lIIIlIl[91] = (0x6C ^ 0x4D) << " ".length();
        el.lIIIlIl[92] = 0x17 ^ 0x54;
        el.lIIIlIl[93] = -(0x99 ^ 0xC2);
        el.lIIIlIl[94] = (0x3E ^ 0x2F) << (" ".length() << " ".length());
        el.lIIIlIl[95] = 0xF1 ^ 0xB4;
        el.lIIIlIl[96] = 0xD4 ^ 0x9D;
        el.lIIIlIl[97] = (0x41 ^ 0x64) << " ".length();
        el.lIIIlIl[98] = 0xCD ^ 0x86;
        el.lIIIlIl[99] = 5385 + 90235 - 4956 + 9335;
        el.lIIIlIl[100] = (0x6B ^ 0x50) << " ".length();
        el.lIIIlIl[101] = (0x7D ^ 0x66) << (" ".length() << " ".length());
        el.lIIIlIl[102] = -(0x7B ^ 0x2B);
        el.lIIIlIl[103] = -(0x62 ^ 0x42);
        el.lIIIlIl[104] = -(0x16 ^ 0x5F);
        el.lIIIlIl[105] = -(0x9D ^ 0x91);
    }
}

