/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.microedition.lcdui.ChoiceGroup
 *  javax.microedition.lcdui.Command
 *  javax.microedition.lcdui.CommandListener
 *  javax.microedition.lcdui.Display
 *  javax.microedition.lcdui.Displayable
 *  javax.microedition.lcdui.Form
 *  javax.microedition.lcdui.Item
 *  javax.microedition.lcdui.ItemStateListener
 *  javax.microedition.lcdui.TextField
 *  javax.microedition.midlet.MIDlet
 */
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import javax.microedition.lcdui.ChoiceGroup;
import javax.microedition.lcdui.Command;
import javax.microedition.lcdui.CommandListener;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import javax.microedition.lcdui.Form;
import javax.microedition.lcdui.Item;
import javax.microedition.lcdui.ItemStateListener;
import javax.microedition.lcdui.TextField;
import javax.microedition.midlet.MIDlet;

public class em
extends Form
implements CommandListener,
ItemStateListener {
    private /* synthetic */ Command i;
    private /* synthetic */ ChoiceGroup j;
    private /* synthetic */ ChoiceGroup k;
    private /* synthetic */ TextField[] l;
    private /* synthetic */ TextField m;
    public static /* synthetic */ String a;
    public static /* synthetic */ String b;
    public static /* synthetic */ String c;
    public static /* synthetic */ String d;
    public static /* synthetic */ String e;
    public static /* synthetic */ String f;
    public static /* synthetic */ boolean g;
    public static /* synthetic */ boolean h;
    private static final /* synthetic */ int[] llllIlI;

    static {
        em.lIllllI();
        a = "";
        b = "";
        c = "";
        d = "";
        e = "";
        f = "";
    }

    public em(String string) {
        super(string);
        em llIllllllIlllll;
        byte[] byArray = new byte[llllIlI[0]];
        byArray[em.llllIlI[1]] = llllIlI[1];
        byArray[em.llllIlI[2]] = llllIlI[3];
        byArray[em.llllIlI[4]] = llllIlI[1];
        byArray[em.llllIlI[5]] = llllIlI[6];
        byArray[em.llllIlI[7]] = llllIlI[1];
        byArray[em.llllIlI[8]] = llllIlI[9];
        byArray[em.llllIlI[10]] = llllIlI[1];
        byArray[em.llllIlI[11]] = llllIlI[12];
        byArray[em.llllIlI[13]] = llllIlI[1];
        byArray[em.llllIlI[14]] = llllIlI[15];
        byArray[em.llllIlI[16]] = llllIlI[1];
        byArray[em.llllIlI[17]] = llllIlI[18];
        byArray[em.llllIlI[19]] = llllIlI[1];
        byArray[em.llllIlI[20]] = llllIlI[21];
        byArray[em.llllIlI[22]] = llllIlI[1];
        byArray[em.llllIlI[23]] = llllIlI[9];
        byArray[em.llllIlI[24]] = llllIlI[1];
        byArray[em.llllIlI[25]] = llllIlI[26];
        byArray[em.llllIlI[27]] = llllIlI[1];
        byArray[em.llllIlI[28]] = llllIlI[29];
        byArray[em.llllIlI[30]] = llllIlI[1];
        byArray[em.llllIlI[31]] = llllIlI[9];
        byArray[em.llllIlI[32]] = llllIlI[1];
        byArray[em.llllIlI[33]] = llllIlI[26];
        byArray[em.llllIlI[34]] = llllIlI[2];
        byArray[em.llllIlI[35]] = llllIlI[36];
        byArray[em.llllIlI[37]] = llllIlI[38];
        byArray[em.llllIlI[39]] = llllIlI[40];
        byArray[em.llllIlI[41]] = llllIlI[1];
        byArray[em.llllIlI[42]] = llllIlI[43];
        byArray[em.llllIlI[38]] = llllIlI[1];
        byArray[em.llllIlI[44]] = llllIlI[45];
        byArray[em.llllIlI[9]] = llllIlI[1];
        byArray[em.llllIlI[46]] = llllIlI[12];
        byArray[em.llllIlI[47]] = llllIlI[1];
        byArray[em.llllIlI[48]] = llllIlI[15];
        byArray[em.llllIlI[49]] = llllIlI[1];
        byArray[em.llllIlI[50]] = llllIlI[51];
        byArray[em.llllIlI[52]] = llllIlI[1];
        byArray[em.llllIlI[53]] = llllIlI[54];
        byArray[em.llllIlI[45]] = llllIlI[1];
        byArray[em.llllIlI[55]] = llllIlI[15];
        byArray[em.llllIlI[56]] = llllIlI[1];
        byArray[em.llllIlI[57]] = llllIlI[9];
        byArray[em.llllIlI[58]] = llllIlI[1];
        byArray[em.llllIlI[59]] = llllIlI[60];
        byArray[em.llllIlI[61]] = llllIlI[1];
        byArray[em.llllIlI[62]] = llllIlI[43];
        byArray[em.llllIlI[63]] = llllIlI[1];
        byArray[em.llllIlI[64]] = llllIlI[65];
        byArray[em.llllIlI[66]] = llllIlI[1];
        byArray[em.llllIlI[67]] = llllIlI[54];
        byArray[em.llllIlI[68]] = llllIlI[1];
        byArray[em.llllIlI[69]] = llllIlI[9];
        byArray[em.llllIlI[70]] = llllIlI[1];
        byArray[em.llllIlI[71]] = llllIlI[12];
        byArray[em.llllIlI[72]] = llllIlI[1];
        byArray[em.llllIlI[73]] = llllIlI[15];
        byArray[em.llllIlI[74]] = llllIlI[1];
        byArray[em.llllIlI[75]] = llllIlI[76];
        byArray[em.llllIlI[77]] = llllIlI[1];
        byArray[em.llllIlI[78]] = llllIlI[9];
        byArray[em.llllIlI[79]] = llllIlI[1];
        byArray[em.llllIlI[80]] = llllIlI[81];
        byArray[em.llllIlI[82]] = llllIlI[1];
        byArray[em.llllIlI[83]] = llllIlI[21];
        byArray[em.llllIlI[84]] = llllIlI[1];
        byArray[em.llllIlI[85]] = llllIlI[9];
        byArray[em.llllIlI[86]] = llllIlI[1];
        byArray[em.llllIlI[87]] = llllIlI[88];
        byArray[em.llllIlI[89]] = llllIlI[38];
        byArray[em.llllIlI[90]] = llllIlI[91];
        byArray[em.llllIlI[92]] = llllIlI[1];
        byArray[em.llllIlI[93]] = llllIlI[54];
        byArray[em.llllIlI[94]] = llllIlI[1];
        byArray[em.llllIlI[95]] = llllIlI[9];
        byArray[em.llllIlI[96]] = llllIlI[2];
        byArray[em.llllIlI[97]] = llllIlI[25];
        byArray[em.llllIlI[98]] = llllIlI[1];
        byArray[em.llllIlI[99]] = llllIlI[43];
        byArray[em.llllIlI[3]] = llllIlI[38];
        byArray[em.llllIlI[100]] = llllIlI[101];
        byArray[em.llllIlI[102]] = llllIlI[1];
        byArray[em.llllIlI[103]] = llllIlI[54];
        byArray[em.llllIlI[6]] = llllIlI[1];
        byArray[em.llllIlI[104]] = llllIlI[55];
        String[] stringArray = new String[llllIlI[4]];
        byte[] byArray2 = new byte[llllIlI[10]];
        byArray2[em.llllIlI[1]] = llllIlI[1];
        byArray2[em.llllIlI[2]] = llllIlI[84];
        byArray2[em.llllIlI[4]] = llllIlI[38];
        byArray2[em.llllIlI[5]] = llllIlI[105];
        byArray2[em.llllIlI[7]] = llllIlI[1];
        byArray2[em.llllIlI[8]] = llllIlI[12];
        stringArray[em.llllIlI[1]] = ec.a(byArray2);
        byte[] byArray3 = new byte[llllIlI[10]];
        byArray3[em.llllIlI[1]] = llllIlI[1];
        byArray3[em.llllIlI[2]] = llllIlI[6];
        byArray3[em.llllIlI[4]] = llllIlI[38];
        byArray3[em.llllIlI[5]] = llllIlI[106];
        byArray3[em.llllIlI[7]] = llllIlI[1];
        byArray3[em.llllIlI[8]] = llllIlI[12];
        stringArray[em.llllIlI[2]] = ec.a(byArray3);
        this.j = new ChoiceGroup(ec.a(byArray), llllIlI[2], stringArray, null);
        this.append((Item)this.j);
        byte[] byArray4 = new byte[llllIlI[30]];
        byArray4[em.llllIlI[1]] = llllIlI[1];
        byArray4[em.llllIlI[2]] = llllIlI[83];
        byArray4[em.llllIlI[4]] = llllIlI[1];
        byArray4[em.llllIlI[5]] = llllIlI[107];
        byArray4[em.llllIlI[7]] = llllIlI[1];
        byArray4[em.llllIlI[8]] = llllIlI[12];
        byArray4[em.llllIlI[10]] = llllIlI[1];
        byArray4[em.llllIlI[11]] = llllIlI[21];
        byArray4[em.llllIlI[13]] = llllIlI[1];
        byArray4[em.llllIlI[14]] = llllIlI[9];
        byArray4[em.llllIlI[16]] = llllIlI[1];
        byArray4[em.llllIlI[17]] = llllIlI[3];
        byArray4[em.llllIlI[19]] = llllIlI[1];
        byArray4[em.llllIlI[20]] = llllIlI[108];
        byArray4[em.llllIlI[22]] = llllIlI[1];
        byArray4[em.llllIlI[23]] = llllIlI[109];
        byArray4[em.llllIlI[24]] = llllIlI[1];
        byArray4[em.llllIlI[25]] = llllIlI[12];
        byArray4[em.llllIlI[27]] = llllIlI[1];
        byArray4[em.llllIlI[28]] = llllIlI[110];
        String[] stringArray2 = new String[llllIlI[4]];
        byte[] byArray5 = new byte[llllIlI[41]];
        byArray5[em.llllIlI[1]] = llllIlI[1];
        byArray5[em.llllIlI[2]] = llllIlI[97];
        byArray5[em.llllIlI[4]] = llllIlI[38];
        byArray5[em.llllIlI[5]] = llllIlI[111];
        byArray5[em.llllIlI[7]] = llllIlI[1];
        byArray5[em.llllIlI[8]] = llllIlI[43];
        byArray5[em.llllIlI[10]] = llllIlI[1];
        byArray5[em.llllIlI[11]] = llllIlI[9];
        byArray5[em.llllIlI[13]] = llllIlI[1];
        byArray5[em.llllIlI[14]] = llllIlI[12];
        byArray5[em.llllIlI[16]] = llllIlI[1];
        byArray5[em.llllIlI[17]] = llllIlI[15];
        byArray5[em.llllIlI[19]] = llllIlI[1];
        byArray5[em.llllIlI[20]] = llllIlI[51];
        byArray5[em.llllIlI[22]] = llllIlI[1];
        byArray5[em.llllIlI[23]] = llllIlI[54];
        byArray5[em.llllIlI[24]] = llllIlI[1];
        byArray5[em.llllIlI[25]] = llllIlI[15];
        byArray5[em.llllIlI[27]] = llllIlI[1];
        byArray5[em.llllIlI[28]] = llllIlI[9];
        byArray5[em.llllIlI[30]] = llllIlI[1];
        byArray5[em.llllIlI[31]] = llllIlI[60];
        byArray5[em.llllIlI[32]] = llllIlI[1];
        byArray5[em.llllIlI[33]] = llllIlI[43];
        byArray5[em.llllIlI[34]] = llllIlI[1];
        byArray5[em.llllIlI[35]] = llllIlI[65];
        byArray5[em.llllIlI[37]] = llllIlI[1];
        byArray5[em.llllIlI[39]] = llllIlI[54];
        stringArray2[em.llllIlI[1]] = ec.a(byArray5);
        byte[] byArray6 = new byte[llllIlI[34]];
        byArray6[em.llllIlI[1]] = llllIlI[1];
        byArray6[em.llllIlI[2]] = llllIlI[112];
        byArray6[em.llllIlI[4]] = llllIlI[1];
        byArray6[em.llllIlI[5]] = llllIlI[43];
        byArray6[em.llllIlI[7]] = llllIlI[1];
        byArray6[em.llllIlI[8]] = llllIlI[54];
        byArray6[em.llllIlI[10]] = llllIlI[1];
        byArray6[em.llllIlI[11]] = llllIlI[9];
        byArray6[em.llllIlI[13]] = llllIlI[1];
        byArray6[em.llllIlI[14]] = llllIlI[60];
        byArray6[em.llllIlI[16]] = llllIlI[1];
        byArray6[em.llllIlI[17]] = llllIlI[51];
        byArray6[em.llllIlI[19]] = llllIlI[1];
        byArray6[em.llllIlI[20]] = llllIlI[21];
        byArray6[em.llllIlI[22]] = llllIlI[1];
        byArray6[em.llllIlI[23]] = llllIlI[9];
        byArray6[em.llllIlI[24]] = llllIlI[1];
        byArray6[em.llllIlI[25]] = llllIlI[54];
        byArray6[em.llllIlI[27]] = llllIlI[1];
        byArray6[em.llllIlI[28]] = llllIlI[15];
        byArray6[em.llllIlI[30]] = llllIlI[1];
        byArray6[em.llllIlI[31]] = llllIlI[113];
        byArray6[em.llllIlI[32]] = llllIlI[1];
        byArray6[em.llllIlI[33]] = llllIlI[114];
        stringArray2[em.llllIlI[2]] = ec.a(byArray6);
        this.k = new ChoiceGroup(ec.a(byArray4), llllIlI[2], stringArray2, null);
        this.append((Item)this.k);
        this.setItemStateListener(this);
        TextField[] textFieldArray = new TextField[llllIlI[8]];
        byte[] byArray7 = new byte[llllIlI[34]];
        byArray7[em.llllIlI[1]] = llllIlI[1];
        byArray7[em.llllIlI[2]] = llllIlI[6];
        byArray7[em.llllIlI[4]] = llllIlI[1];
        byArray7[em.llllIlI[5]] = llllIlI[15];
        byArray7[em.llllIlI[7]] = llllIlI[1];
        byArray7[em.llllIlI[8]] = llllIlI[51];
        byArray7[em.llllIlI[10]] = llllIlI[1];
        byArray7[em.llllIlI[11]] = llllIlI[54];
        byArray7[em.llllIlI[13]] = llllIlI[1];
        byArray7[em.llllIlI[14]] = llllIlI[15];
        byArray7[em.llllIlI[16]] = llllIlI[1];
        byArray7[em.llllIlI[17]] = llllIlI[9];
        byArray7[em.llllIlI[19]] = llllIlI[1];
        byArray7[em.llllIlI[20]] = llllIlI[60];
        byArray7[em.llllIlI[22]] = llllIlI[1];
        byArray7[em.llllIlI[23]] = llllIlI[43];
        byArray7[em.llllIlI[24]] = llllIlI[1];
        byArray7[em.llllIlI[25]] = llllIlI[65];
        byArray7[em.llllIlI[27]] = llllIlI[1];
        byArray7[em.llllIlI[28]] = llllIlI[54];
        byArray7[em.llllIlI[30]] = llllIlI[1];
        byArray7[em.llllIlI[31]] = llllIlI[9];
        byArray7[em.llllIlI[32]] = llllIlI[1];
        byArray7[em.llllIlI[33]] = llllIlI[64];
        textFieldArray[em.llllIlI[1]] = new TextField(ec.a(byArray7), a, llllIlI[115], llllIlI[1]);
        byte[] byArray8 = new byte[llllIlI[34]];
        byArray8[em.llllIlI[1]] = llllIlI[1];
        byArray8[em.llllIlI[2]] = llllIlI[6];
        byArray8[em.llllIlI[4]] = llllIlI[1];
        byArray8[em.llllIlI[5]] = llllIlI[15];
        byArray8[em.llllIlI[7]] = llllIlI[1];
        byArray8[em.llllIlI[8]] = llllIlI[51];
        byArray8[em.llllIlI[10]] = llllIlI[1];
        byArray8[em.llllIlI[11]] = llllIlI[54];
        byArray8[em.llllIlI[13]] = llllIlI[1];
        byArray8[em.llllIlI[14]] = llllIlI[15];
        byArray8[em.llllIlI[16]] = llllIlI[1];
        byArray8[em.llllIlI[17]] = llllIlI[9];
        byArray8[em.llllIlI[19]] = llllIlI[1];
        byArray8[em.llllIlI[20]] = llllIlI[60];
        byArray8[em.llllIlI[22]] = llllIlI[1];
        byArray8[em.llllIlI[23]] = llllIlI[43];
        byArray8[em.llllIlI[24]] = llllIlI[1];
        byArray8[em.llllIlI[25]] = llllIlI[65];
        byArray8[em.llllIlI[27]] = llllIlI[1];
        byArray8[em.llllIlI[28]] = llllIlI[54];
        byArray8[em.llllIlI[30]] = llllIlI[1];
        byArray8[em.llllIlI[31]] = llllIlI[9];
        byArray8[em.llllIlI[32]] = llllIlI[1];
        byArray8[em.llllIlI[33]] = llllIlI[66];
        textFieldArray[em.llllIlI[2]] = new TextField(ec.a(byArray8), b, llllIlI[115], llllIlI[1]);
        byte[] byArray9 = new byte[llllIlI[34]];
        byArray9[em.llllIlI[1]] = llllIlI[1];
        byArray9[em.llllIlI[2]] = llllIlI[6];
        byArray9[em.llllIlI[4]] = llllIlI[1];
        byArray9[em.llllIlI[5]] = llllIlI[15];
        byArray9[em.llllIlI[7]] = llllIlI[1];
        byArray9[em.llllIlI[8]] = llllIlI[51];
        byArray9[em.llllIlI[10]] = llllIlI[1];
        byArray9[em.llllIlI[11]] = llllIlI[54];
        byArray9[em.llllIlI[13]] = llllIlI[1];
        byArray9[em.llllIlI[14]] = llllIlI[15];
        byArray9[em.llllIlI[16]] = llllIlI[1];
        byArray9[em.llllIlI[17]] = llllIlI[9];
        byArray9[em.llllIlI[19]] = llllIlI[1];
        byArray9[em.llllIlI[20]] = llllIlI[60];
        byArray9[em.llllIlI[22]] = llllIlI[1];
        byArray9[em.llllIlI[23]] = llllIlI[43];
        byArray9[em.llllIlI[24]] = llllIlI[1];
        byArray9[em.llllIlI[25]] = llllIlI[65];
        byArray9[em.llllIlI[27]] = llllIlI[1];
        byArray9[em.llllIlI[28]] = llllIlI[54];
        byArray9[em.llllIlI[30]] = llllIlI[1];
        byArray9[em.llllIlI[31]] = llllIlI[9];
        byArray9[em.llllIlI[32]] = llllIlI[1];
        byArray9[em.llllIlI[33]] = llllIlI[67];
        textFieldArray[em.llllIlI[4]] = new TextField(ec.a(byArray9), c, llllIlI[115], llllIlI[1]);
        byte[] byArray10 = new byte[llllIlI[34]];
        byArray10[em.llllIlI[1]] = llllIlI[1];
        byArray10[em.llllIlI[2]] = llllIlI[6];
        byArray10[em.llllIlI[4]] = llllIlI[1];
        byArray10[em.llllIlI[5]] = llllIlI[15];
        byArray10[em.llllIlI[7]] = llllIlI[1];
        byArray10[em.llllIlI[8]] = llllIlI[51];
        byArray10[em.llllIlI[10]] = llllIlI[1];
        byArray10[em.llllIlI[11]] = llllIlI[54];
        byArray10[em.llllIlI[13]] = llllIlI[1];
        byArray10[em.llllIlI[14]] = llllIlI[15];
        byArray10[em.llllIlI[16]] = llllIlI[1];
        byArray10[em.llllIlI[17]] = llllIlI[9];
        byArray10[em.llllIlI[19]] = llllIlI[1];
        byArray10[em.llllIlI[20]] = llllIlI[60];
        byArray10[em.llllIlI[22]] = llllIlI[1];
        byArray10[em.llllIlI[23]] = llllIlI[43];
        byArray10[em.llllIlI[24]] = llllIlI[1];
        byArray10[em.llllIlI[25]] = llllIlI[65];
        byArray10[em.llllIlI[27]] = llllIlI[1];
        byArray10[em.llllIlI[28]] = llllIlI[54];
        byArray10[em.llllIlI[30]] = llllIlI[1];
        byArray10[em.llllIlI[31]] = llllIlI[9];
        byArray10[em.llllIlI[32]] = llllIlI[1];
        byArray10[em.llllIlI[33]] = llllIlI[68];
        textFieldArray[em.llllIlI[5]] = new TextField(ec.a(byArray10), d, llllIlI[115], llllIlI[1]);
        byte[] byArray11 = new byte[llllIlI[34]];
        byArray11[em.llllIlI[1]] = llllIlI[1];
        byArray11[em.llllIlI[2]] = llllIlI[6];
        byArray11[em.llllIlI[4]] = llllIlI[1];
        byArray11[em.llllIlI[5]] = llllIlI[15];
        byArray11[em.llllIlI[7]] = llllIlI[1];
        byArray11[em.llllIlI[8]] = llllIlI[51];
        byArray11[em.llllIlI[10]] = llllIlI[1];
        byArray11[em.llllIlI[11]] = llllIlI[54];
        byArray11[em.llllIlI[13]] = llllIlI[1];
        byArray11[em.llllIlI[14]] = llllIlI[15];
        byArray11[em.llllIlI[16]] = llllIlI[1];
        byArray11[em.llllIlI[17]] = llllIlI[9];
        byArray11[em.llllIlI[19]] = llllIlI[1];
        byArray11[em.llllIlI[20]] = llllIlI[60];
        byArray11[em.llllIlI[22]] = llllIlI[1];
        byArray11[em.llllIlI[23]] = llllIlI[43];
        byArray11[em.llllIlI[24]] = llllIlI[1];
        byArray11[em.llllIlI[25]] = llllIlI[65];
        byArray11[em.llllIlI[27]] = llllIlI[1];
        byArray11[em.llllIlI[28]] = llllIlI[54];
        byArray11[em.llllIlI[30]] = llllIlI[1];
        byArray11[em.llllIlI[31]] = llllIlI[9];
        byArray11[em.llllIlI[32]] = llllIlI[1];
        byArray11[em.llllIlI[33]] = llllIlI[69];
        textFieldArray[em.llllIlI[7]] = new TextField(ec.a(byArray11), e, llllIlI[115], llllIlI[1]);
        this.l = textFieldArray;
        byte[] byArray12 = new byte[llllIlI[32]];
        byArray12[em.llllIlI[1]] = llllIlI[1];
        byArray12[em.llllIlI[2]] = llllIlI[6];
        byArray12[em.llllIlI[4]] = llllIlI[1];
        byArray12[em.llllIlI[5]] = llllIlI[109];
        byArray12[em.llllIlI[7]] = llllIlI[2];
        byArray12[em.llllIlI[8]] = llllIlI[36];
        byArray12[em.llllIlI[10]] = llllIlI[38];
        byArray12[em.llllIlI[11]] = llllIlI[116];
        byArray12[em.llllIlI[13]] = llllIlI[1];
        byArray12[em.llllIlI[14]] = llllIlI[54];
        byArray12[em.llllIlI[16]] = llllIlI[1];
        byArray12[em.llllIlI[17]] = llllIlI[117];
        byArray12[em.llllIlI[19]] = llllIlI[1];
        byArray12[em.llllIlI[20]] = llllIlI[9];
        byArray12[em.llllIlI[22]] = llllIlI[1];
        byArray12[em.llllIlI[23]] = llllIlI[54];
        byArray12[em.llllIlI[24]] = llllIlI[1];
        byArray12[em.llllIlI[25]] = llllIlI[15];
        byArray12[em.llllIlI[27]] = llllIlI[1];
        byArray12[em.llllIlI[28]] = llllIlI[113];
        byArray12[em.llllIlI[30]] = llllIlI[1];
        byArray12[em.llllIlI[31]] = llllIlI[114];
        this.m = new TextField(ec.a(byArray12), f, llllIlI[115], llllIlI[1]);
        byte[] byArray13 = new byte[llllIlI[10]];
        byArray13[em.llllIlI[1]] = llllIlI[1];
        byArray13[em.llllIlI[2]] = llllIlI[96];
        byArray13[em.llllIlI[4]] = llllIlI[2];
        byArray13[em.llllIlI[5]] = llllIlI[36];
        byArray13[em.llllIlI[7]] = llllIlI[1];
        byArray13[em.llllIlI[8]] = llllIlI[107];
        this.i = new Command(ec.a(byArray13), llllIlI[7], llllIlI[1]);
        this.addCommand(this.i);
        byte[] byArray14 = new byte[llllIlI[16]];
        byArray14[em.llllIlI[1]] = llllIlI[1];
        byArray14[em.llllIlI[2]] = llllIlI[6];
        byArray14[em.llllIlI[4]] = llllIlI[1];
        byArray14[em.llllIlI[5]] = llllIlI[15];
        byArray14[em.llllIlI[7]] = llllIlI[1];
        byArray14[em.llllIlI[8]] = llllIlI[21];
        byArray14[em.llllIlI[10]] = llllIlI[1];
        byArray14[em.llllIlI[11]] = llllIlI[118];
        byArray14[em.llllIlI[13]] = llllIlI[1];
        byArray14[em.llllIlI[14]] = llllIlI[12];
        this.addCommand(new Command(ec.a(byArray14), llllIlI[11], llllIlI[1]));
        this.setCommandListener(this);
        this.j.setSelectedIndex(g ? llllIlI[1] : llllIlI[2], llllIlI[2]);
        llIllllllIlllll.k.setSelectedIndex(h ? llllIlI[1] : llllIlI[2], llllIlI[2]);
        this.c();
    }

    public static void a() {
        byte[] byArray = new byte[llllIlI[34]];
        byArray[em.llllIlI[1]] = llllIlI[1];
        byArray[em.llllIlI[2]] = llllIlI[85];
        byArray[em.llllIlI[4]] = llllIlI[1];
        byArray[em.llllIlI[5]] = llllIlI[51];
        byArray[em.llllIlI[7]] = llllIlI[1];
        byArray[em.llllIlI[8]] = llllIlI[43];
        byArray[em.llllIlI[10]] = llllIlI[1];
        byArray[em.llllIlI[11]] = llllIlI[9];
        byArray[em.llllIlI[13]] = llllIlI[2];
        byArray[em.llllIlI[14]] = llllIlI[25];
        byArray[em.llllIlI[16]] = llllIlI[38];
        byArray[em.llllIlI[17]] = llllIlI[119];
        byArray[em.llllIlI[19]] = llllIlI[1];
        byArray[em.llllIlI[20]] = llllIlI[12];
        byArray[em.llllIlI[22]] = llllIlI[1];
        byArray[em.llllIlI[23]] = llllIlI[9];
        byArray[em.llllIlI[24]] = llllIlI[1];
        byArray[em.llllIlI[25]] = llllIlI[54];
        byArray[em.llllIlI[27]] = llllIlI[1];
        byArray[em.llllIlI[28]] = llllIlI[15];
        byArray[em.llllIlI[30]] = llllIlI[1];
        byArray[em.llllIlI[31]] = llllIlI[113];
        byArray[em.llllIlI[32]] = llllIlI[1];
        byArray[em.llllIlI[33]] = llllIlI[114];
        Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)new em(ec.a(byArray)));
    }

    /*
     * WARNING - void declaration
     */
    public static void b() {
        byte[] byArray = new byte[llllIlI[27]];
        byArray[em.llllIlI[1]] = llllIlI[1];
        byArray[em.llllIlI[2]] = llllIlI[120];
        byArray[em.llllIlI[4]] = llllIlI[1];
        byArray[em.llllIlI[5]] = llllIlI[12];
        byArray[em.llllIlI[7]] = llllIlI[1];
        byArray[em.llllIlI[8]] = llllIlI[103];
        byArray[em.llllIlI[10]] = llllIlI[1];
        byArray[em.llllIlI[11]] = llllIlI[18];
        byArray[em.llllIlI[13]] = llllIlI[1];
        byArray[em.llllIlI[14]] = llllIlI[12];
        byArray[em.llllIlI[16]] = llllIlI[1];
        byArray[em.llllIlI[17]] = llllIlI[12];
        byArray[em.llllIlI[19]] = llllIlI[1];
        byArray[em.llllIlI[20]] = llllIlI[43];
        byArray[em.llllIlI[22]] = llllIlI[1];
        byArray[em.llllIlI[23]] = llllIlI[54];
        byArray[em.llllIlI[24]] = llllIlI[1];
        byArray[em.llllIlI[25]] = llllIlI[117];
        byte[] byArray2 = dv.a(ec.a(byArray));
        if (byArray2 != null) {
            ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(byArray2);
            DataInputStream llIllllllIlIlll = new DataInputStream(byteArrayInputStream);
            try {
                void llIllllllIllIII;
                a = llIllllllIlIlll.readUTF();
                b = llIllllllIlIlll.readUTF();
                c = llIllllllIlIlll.readUTF();
                d = llIllllllIlIlll.readUTF();
                e = llIllllllIlIlll.readUTF();
                f = llIllllllIlIlll.readUTF();
                g = llIllllllIlIlll.readBoolean();
                h = llIllllllIlIlll.readBoolean();
                llIllllllIlIlll.close();
                llIllllllIllIII.close();
            }
            catch (Exception exception) {
                // empty catch block
            }
        }
    }

    private void c() {
        em llIllllllIlIIII;
        while (llIllllllIlIIII.size() > llllIlI[4]) {
            llIllllllIlIIII.delete(llllIlI[4]);
        }
        if (h) {
            TextField[] llIllllllIIllII = llIllllllIlIIII.l;
            int llIllllllIIllIl = llIllllllIlIIII.l.length;
            int llIllllllIIlllI = llllIlI[1];
            while (llIllllllIIlllI < llIllllllIIllIl) {
                TextField llIllllllIIllll = llIllllllIIllII[llIllllllIIlllI];
                llIllllllIlIIII.append((Item)llIllllllIIllll);
                ++llIllllllIIlllI;
            }
        } else {
            llIllllllIlIIII.append((Item)llIllllllIlIIII.m);
        }
    }

    /*
     * WARNING - void declaration
     */
    public void commandAction(Command command, Displayable displayable) {
        if (command == this.i) {
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            DataOutputStream llIllllllIIIIll = new DataOutputStream(byteArrayOutputStream);
            try {
                void llIllllllIIIlII;
                em llIllllllIIIllI;
                g = llIllllllIIIllI.j.getSelectedIndex() == 0 ? llllIlI[2] : llllIlI[1];
                h = llIllllllIIIllI.k.getSelectedIndex() == 0 ? llllIlI[2] : llllIlI[1];
                a = llIllllllIIIllI.l[llllIlI[1]].getString().trim();
                b = llIllllllIIIllI.l[llllIlI[2]].getString().trim();
                c = llIllllllIIIllI.l[llllIlI[4]].getString().trim();
                d = llIllllllIIIllI.l[llllIlI[5]].getString().trim();
                e = llIllllllIIIllI.l[llllIlI[7]].getString().trim();
                f = llIllllllIIIllI.m.getString().trim();
                llIllllllIIIIll.writeUTF(a);
                llIllllllIIIIll.writeUTF(b);
                llIllllllIIIIll.writeUTF(c);
                llIllllllIIIIll.writeUTF(d);
                llIllllllIIIIll.writeUTF(e);
                llIllllllIIIIll.writeUTF(f);
                llIllllllIIIIll.writeBoolean(g);
                llIllllllIIIIll.writeBoolean(h);
                byte[] byArray = new byte[llllIlI[27]];
                byArray[em.llllIlI[1]] = llllIlI[1];
                byArray[em.llllIlI[2]] = llllIlI[120];
                byArray[em.llllIlI[4]] = llllIlI[1];
                byArray[em.llllIlI[5]] = llllIlI[12];
                byArray[em.llllIlI[7]] = llllIlI[1];
                byArray[em.llllIlI[8]] = llllIlI[103];
                byArray[em.llllIlI[10]] = llllIlI[1];
                byArray[em.llllIlI[11]] = llllIlI[18];
                byArray[em.llllIlI[13]] = llllIlI[1];
                byArray[em.llllIlI[14]] = llllIlI[12];
                byArray[em.llllIlI[16]] = llllIlI[1];
                byArray[em.llllIlI[17]] = llllIlI[12];
                byArray[em.llllIlI[19]] = llllIlI[1];
                byArray[em.llllIlI[20]] = llllIlI[43];
                byArray[em.llllIlI[22]] = llllIlI[1];
                byArray[em.llllIlI[23]] = llllIlI[54];
                byArray[em.llllIlI[24]] = llllIlI[1];
                byArray[em.llllIlI[25]] = llllIlI[117];
                dv.a(ec.a(byArray), ((ByteArrayOutputStream)llIllllllIIIlII).toByteArray());
                llIllllllIIIIll.flush();
                llIllllllIIIlII.flush();
                byte[] byArray2 = new byte[llllIlI[58]];
                byArray2[em.llllIlI[1]] = llllIlI[1];
                byArray2[em.llllIlI[2]] = llllIlI[96];
                byArray2[em.llllIlI[4]] = llllIlI[2];
                byArray2[em.llllIlI[5]] = llllIlI[36];
                byArray2[em.llllIlI[7]] = llllIlI[1];
                byArray2[em.llllIlI[8]] = llllIlI[107];
                byArray2[em.llllIlI[10]] = llllIlI[1];
                byArray2[em.llllIlI[11]] = llllIlI[9];
                byArray2[em.llllIlI[13]] = llllIlI[1];
                byArray2[em.llllIlI[14]] = llllIlI[88];
                byArray2[em.llllIlI[16]] = llllIlI[1];
                byArray2[em.llllIlI[17]] = llllIlI[51];
                byArray2[em.llllIlI[19]] = llllIlI[1];
                byArray2[em.llllIlI[20]] = llllIlI[43];
                byArray2[em.llllIlI[22]] = llllIlI[1];
                byArray2[em.llllIlI[23]] = llllIlI[9];
                byArray2[em.llllIlI[24]] = llllIlI[2];
                byArray2[em.llllIlI[25]] = llllIlI[25];
                byArray2[em.llllIlI[27]] = llllIlI[38];
                byArray2[em.llllIlI[28]] = llllIlI[119];
                byArray2[em.llllIlI[30]] = llllIlI[1];
                byArray2[em.llllIlI[31]] = llllIlI[12];
                byArray2[em.llllIlI[32]] = llllIlI[1];
                byArray2[em.llllIlI[33]] = llllIlI[9];
                byArray2[em.llllIlI[34]] = llllIlI[1];
                byArray2[em.llllIlI[35]] = llllIlI[12];
                byArray2[em.llllIlI[37]] = llllIlI[1];
                byArray2[em.llllIlI[39]] = llllIlI[15];
                byArray2[em.llllIlI[41]] = llllIlI[1];
                byArray2[em.llllIlI[42]] = llllIlI[51];
                byArray2[em.llllIlI[38]] = llllIlI[1];
                byArray2[em.llllIlI[44]] = llllIlI[54];
                byArray2[em.llllIlI[9]] = llllIlI[1];
                byArray2[em.llllIlI[46]] = llllIlI[15];
                byArray2[em.llllIlI[47]] = llllIlI[1];
                byArray2[em.llllIlI[48]] = llllIlI[9];
                byArray2[em.llllIlI[49]] = llllIlI[1];
                byArray2[em.llllIlI[50]] = llllIlI[88];
                byArray2[em.llllIlI[52]] = llllIlI[1];
                byArray2[em.llllIlI[53]] = llllIlI[121];
                byArray2[em.llllIlI[45]] = llllIlI[1];
                byArray2[em.llllIlI[55]] = llllIlI[54];
                byArray2[em.llllIlI[56]] = llllIlI[1];
                byArray2[em.llllIlI[57]] = llllIlI[117];
                at.a(ec.a(byArray2));
            }
            catch (Exception llIllllllIIIIlI) {
                // empty catch block
            }
        }
        Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)dc.a);
    }

    public void itemStateChanged(Item item) {
        if (item == this.k) {
            em llIlllllIllllll;
            h = this.k.getSelectedIndex() == 0 ? llllIlI[2] : llllIlI[1];
            llIlllllIllllll.c();
        }
    }

    private static void lIllllI() {
        llllIlI = new int[122];
        em.llllIlI[0] = (0x48 ^ 0x63) << " ".length();
        em.llllIlI[1] = (0x1A ^ 0x53) & ~(0xE1 ^ 0xA8);
        em.llllIlI[2] = " ".length();
        em.llllIlI[3] = (9 ^ 0xC) << (" ".length() << (" ".length() << " ".length()));
        em.llllIlI[4] = " ".length() << " ".length();
        em.llllIlI[5] = "   ".length();
        em.llllIlI[6] = (0xAC ^ 0xB9) << (" ".length() << " ".length());
        em.llllIlI[7] = " ".length() << (" ".length() << " ".length());
        em.llllIlI[8] = 2 ^ 7;
        em.llllIlI[9] = " ".length() << (0xA9 ^ 0xAC);
        em.llllIlI[10] = "   ".length() << " ".length();
        em.llllIlI[11] = 0xC2 ^ 0xC5;
        em.llllIlI[12] = (0x2C ^ 0x31) << (" ".length() << " ".length());
        em.llllIlI[13] = " ".length() << "   ".length();
        em.llllIlI[14] = 0x4F ^ 0x46;
        em.llllIlI[15] = (0xCA ^ 0xC7) << "   ".length();
        em.llllIlI[16] = (0x45 ^ 0x40) << " ".length();
        em.llllIlI[17] = 0x34 ^ 0x3F;
        em.llllIlI[18] = 0x61 ^ 4;
        em.llllIlI[19] = "   ".length() << (" ".length() << " ".length());
        em.llllIlI[20] = 3 ^ 0xE;
        em.llllIlI[21] = 0x51 ^ 0x3E;
        em.llllIlI[22] = (0x97 ^ 0x90) << " ".length();
        em.llllIlI[23] = 0xB3 ^ 0xBC;
        em.llllIlI[24] = " ".length() << (" ".length() << (" ".length() << " ".length()));
        em.llllIlI[25] = 0x6A ^ 0x7B;
        em.llllIlI[26] = (0x2E ^ 0x37) << (" ".length() << " ".length());
        em.llllIlI[27] = (0x98 ^ 0x91) << " ".length();
        em.llllIlI[28] = 0x90 ^ 0x83;
        em.llllIlI[29] = 0x61 ^ 0x12;
        em.llllIlI[30] = (0x2A ^ 0x2F) << (" ".length() << " ".length());
        em.llllIlI[31] = 0x65 ^ 0x70;
        em.llllIlI[32] = (0x97 ^ 0x9C) << " ".length();
        em.llllIlI[33] = 0xB4 ^ 0xA3;
        em.llllIlI[34] = "   ".length() << "   ".length();
        em.llllIlI[35] = 0x78 ^ 0x61;
        em.llllIlI[36] = -(0xC3 ^ 0x93);
        em.llllIlI[37] = (0xA3 ^ 0xAE) << " ".length();
        em.llllIlI[38] = (0x68 ^ 0x67) << " ".length();
        em.llllIlI[39] = 0x47 ^ 0x5C;
        em.llllIlI[40] = -(0x44 ^ 0x61);
        em.llllIlI[41] = (9 ^ 0xE) << (" ".length() << " ".length());
        em.llllIlI[42] = 0xBB ^ 0xA6;
        em.llllIlI[43] = 0xFB ^ 0x92;
        em.llllIlI[44] = 0xA9 ^ 0xB6;
        em.llllIlI[45] = (0xC6 ^ 0xC3) << "   ".length();
        em.llllIlI[46] = 0 ^ 0x21;
        em.llllIlI[47] = (0x28 ^ 0x39) << " ".length();
        em.llllIlI[48] = 0xBE ^ 0x9D;
        em.llllIlI[49] = (0x56 ^ 0x5F) << (" ".length() << " ".length());
        em.llllIlI[50] = 0x2C ^ 9;
        em.llllIlI[51] = -(0x31 ^ 0x11);
        em.llllIlI[52] = (0x81 ^ 0x92) << " ".length();
        em.llllIlI[53] = 0x1F ^ 0x38;
        em.llllIlI[54] = (0xA8 ^ 0x9F) << " ".length();
        em.llllIlI[55] = 0x95 ^ 0xBC;
        em.llllIlI[56] = (0xF ^ 0x1A) << " ".length();
        em.llllIlI[57] = 0x36 ^ 0x1D;
        em.llllIlI[58] = (0xD ^ 6) << (" ".length() << " ".length());
        em.llllIlI[59] = 0xE8 ^ 0xC5;
        em.llllIlI[60] = (0xB ^ 0x30) << " ".length();
        em.llllIlI[61] = (0x92 ^ 0x85) << " ".length();
        em.llllIlI[62] = 0x24 ^ 0xB;
        em.llllIlI[63] = "   ".length() << (" ".length() << (" ".length() << " ".length()));
        em.llllIlI[64] = 0x4B ^ 0x7A;
        em.llllIlI[65] = -(0xB1 ^ 0xA7);
        em.llllIlI[66] = (0x69 ^ 0x70) << " ".length();
        em.llllIlI[67] = 0x51 ^ 0x62;
        em.llllIlI[68] = (0x44 ^ 0x49) << (" ".length() << " ".length());
        em.llllIlI[69] = 0x35 ^ 0;
        em.llllIlI[70] = (0x10 ^ 0xB) << " ".length();
        em.llllIlI[71] = 0x79 ^ 0x4E;
        em.llllIlI[72] = (0x40 ^ 0x47) << "   ".length();
        em.llllIlI[73] = 0x7E ^ 0x47;
        em.llllIlI[74] = (0x1C ^ 1) << " ".length();
        em.llllIlI[75] = 0x19 ^ 0x22;
        em.llllIlI[76] = -(0xD0 ^ 0xC4);
        em.llllIlI[77] = (0xB8 ^ 0xB7) << (" ".length() << " ".length());
        em.llllIlI[78] = 0x97 ^ 0xAA;
        em.llllIlI[79] = (0xAC ^ 0xB3) << " ".length();
        em.llllIlI[80] = 0x1E ^ 0x21;
        em.llllIlI[81] = 0x57 ^ 0x3C;
        em.llllIlI[82] = " ".length() << ("   ".length() << " ".length());
        em.llllIlI[83] = 0xC4 ^ 0x85;
        em.llllIlI[84] = (0x26 ^ 7) << " ".length();
        em.llllIlI[85] = 0x2F ^ 0x6C;
        em.llllIlI[86] = (0x33 ^ 0x22) << (" ".length() << " ".length());
        em.llllIlI[87] = 0xE5 ^ 0xA0;
        em.llllIlI[88] = 0xE2 ^ 0x81;
        em.llllIlI[89] = (0x11 ^ 0x32) << " ".length();
        em.llllIlI[90] = 0xE1 ^ 0xA6;
        em.llllIlI[91] = -(0xEE ^ 0xB7);
        em.llllIlI[92] = (0x9E ^ 0x97) << "   ".length();
        em.llllIlI[93] = 0x76 ^ 0x3F;
        em.llllIlI[94] = (0x80 ^ 0xA5) << " ".length();
        em.llllIlI[95] = 0x6C ^ 0x27;
        em.llllIlI[96] = (0x3A ^ 0x29) << (" ".length() << " ".length());
        em.llllIlI[97] = 0xD0 ^ 0x9D;
        em.llllIlI[98] = (0xE5 ^ 0xC2) << " ".length();
        em.llllIlI[99] = 0xDF ^ 0x90;
        em.llllIlI[100] = 0x94 ^ 0xC5;
        em.llllIlI[101] = -(0x56 ^ 0x69);
        em.llllIlI[102] = (0xB8 ^ 0x91) << " ".length();
        em.llllIlI[103] = 0x79 ^ 0x2A;
        em.llllIlI[104] = 0x78 ^ 0x2D;
        em.llllIlI[105] = -(0x7A ^ 0x29);
        em.llllIlI[106] = -(0x58 ^ 9);
        em.llllIlI[107] = 0x55 ^ 0x20;
        em.llllIlI[108] = 0xD7 ^ 0xB6;
        em.llllIlI[109] = (0x6C ^ 0x55) << " ".length();
        em.llllIlI[110] = 0xEA ^ 0x93;
        em.llllIlI[111] = -(2 ^ 0x21);
        em.llllIlI[112] = (0x2E ^ 0x25) << "   ".length();
        em.llllIlI[113] = -(0x42 ^ 0x4F);
        em.llllIlI[114] = 0x34 ^ 0x59;
        em.llllIlI[115] = 544046 + 879001 - 1048986 + 625938;
        em.llllIlI[116] = -(0xA4 ^ 0x85);
        em.llllIlI[117] = 0xED ^ 0x8A;
        em.llllIlI[118] = -(0x4E ^ 0x51);
        em.llllIlI[119] = -(7 ^ 0x4E);
        em.llllIlI[120] = (0x23 ^ 0x24) << (" ".length() << (" ".length() << " ".length()));
        em.llllIlI[121] = -(0x4E ^ 0x42);
    }
}

