/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.microedition.lcdui.ChoiceGroup
 *  javax.microedition.lcdui.Command
 *  javax.microedition.lcdui.CommandListener
 *  javax.microedition.lcdui.Display
 *  javax.microedition.lcdui.Displayable
 *  javax.microedition.lcdui.Form
 *  javax.microedition.lcdui.Item
 *  javax.microedition.lcdui.TextField
 *  javax.microedition.midlet.MIDlet
 */
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import javax.microedition.lcdui.ChoiceGroup;
import javax.microedition.lcdui.Command;
import javax.microedition.lcdui.CommandListener;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import javax.microedition.lcdui.Form;
import javax.microedition.lcdui.Item;
import javax.microedition.lcdui.TextField;
import javax.microedition.midlet.MIDlet;

public class en
extends Form
implements CommandListener {
    private /* synthetic */ TextField h;
    private /* synthetic */ TextField i;
    private /* synthetic */ TextField j;
    private /* synthetic */ TextField k;
    public static /* synthetic */ int a;
    public static /* synthetic */ int b;
    public static /* synthetic */ int c;
    private static /* synthetic */ String l;
    private static /* synthetic */ String m;
    private /* synthetic */ Command n;
    public static /* synthetic */ dh d;
    private /* synthetic */ ChoiceGroup o;
    private /* synthetic */ ChoiceGroup p;
    private /* synthetic */ ChoiceGroup q;
    public static /* synthetic */ boolean e;
    public static /* synthetic */ boolean f;
    public static /* synthetic */ boolean g;
    private static final /* synthetic */ int[] lIIII;

    static {
        en.lIIIl();
        a = lIIII[0];
        b = lIIII[0];
        c = lIIII[0];
        d = new dh();
    }

    public en(String string) {
        super(string);
        en llllllIllIlIllI;
        byte[] byArray = new byte[lIIII[1]];
        byArray[en.lIIII[0]] = lIIII[0];
        byArray[en.lIIII[2]] = lIIII[3];
        byArray[en.lIIII[4]] = lIIII[0];
        byArray[en.lIIII[5]] = lIIII[6];
        byArray[en.lIIII[7]] = lIIII[0];
        byArray[en.lIIII[8]] = lIIII[9];
        byArray[en.lIIII[10]] = lIIII[0];
        byArray[en.lIIII[11]] = lIIII[12];
        byArray[en.lIIII[13]] = lIIII[0];
        byArray[en.lIIII[14]] = lIIII[15];
        byArray[en.lIIII[16]] = lIIII[0];
        byArray[en.lIIII[17]] = lIIII[18];
        byArray[en.lIIII[19]] = lIIII[0];
        byArray[en.lIIII[20]] = lIIII[21];
        byArray[en.lIIII[22]] = lIIII[0];
        byArray[en.lIIII[23]] = lIIII[9];
        byArray[en.lIIII[24]] = lIIII[0];
        byArray[en.lIIII[25]] = lIIII[26];
        byArray[en.lIIII[27]] = lIIII[0];
        byArray[en.lIIII[28]] = lIIII[18];
        byArray[en.lIIII[29]] = lIIII[0];
        byArray[en.lIIII[30]] = lIIII[12];
        byArray[en.lIIII[31]] = lIIII[0];
        byArray[en.lIIII[32]] = lIIII[12];
        byArray[en.lIIII[33]] = lIIII[0];
        byArray[en.lIIII[34]] = lIIII[35];
        byArray[en.lIIII[36]] = lIIII[0];
        byArray[en.lIIII[37]] = lIIII[38];
        byArray[en.lIIII[39]] = lIIII[0];
        byArray[en.lIIII[40]] = lIIII[41];
        String[] stringArray = new String[lIIII[4]];
        byte[] byArray2 = new byte[lIIII[10]];
        byArray2[en.lIIII[0]] = lIIII[0];
        byArray2[en.lIIII[2]] = lIIII[42];
        byArray2[en.lIIII[4]] = lIIII[1];
        byArray2[en.lIIII[5]] = lIIII[43];
        byArray2[en.lIIII[7]] = lIIII[0];
        byArray2[en.lIIII[8]] = lIIII[12];
        stringArray[en.lIIII[0]] = ec.a(byArray2);
        byte[] byArray3 = new byte[lIIII[10]];
        byArray3[en.lIIII[0]] = lIIII[0];
        byArray3[en.lIIII[2]] = lIIII[44];
        byArray3[en.lIIII[4]] = lIIII[1];
        byArray3[en.lIIII[5]] = lIIII[45];
        byArray3[en.lIIII[7]] = lIIII[0];
        byArray3[en.lIIII[8]] = lIIII[12];
        stringArray[en.lIIII[2]] = ec.a(byArray3);
        this.p = new ChoiceGroup(ec.a(byArray), lIIII[2], stringArray, null);
        this.append((Item)this.p);
        byte[] byArray4 = new byte[lIIII[19]];
        byArray4[en.lIIII[0]] = lIIII[0];
        byArray4[en.lIIII[2]] = lIIII[46];
        byArray4[en.lIIII[4]] = lIIII[0];
        byArray4[en.lIIII[5]] = lIIII[47];
        byArray4[en.lIIII[7]] = lIIII[0];
        byArray4[en.lIIII[8]] = lIIII[6];
        byArray4[en.lIIII[10]] = lIIII[0];
        byArray4[en.lIIII[11]] = lIIII[9];
        byArray4[en.lIIII[13]] = lIIII[0];
        byArray4[en.lIIII[14]] = lIIII[48];
        byArray4[en.lIIII[16]] = lIIII[0];
        byArray4[en.lIIII[17]] = lIIII[6];
        this.h = new TextField(ec.a(byArray4), String.valueOf(a), lIIII[14], lIIII[4]);
        this.append((Item)this.h);
        byte[] byArray5 = new byte[lIIII[49]];
        byArray5[en.lIIII[0]] = lIIII[2];
        byArray5[en.lIIII[2]] = lIIII[24];
        byArray5[en.lIIII[4]] = lIIII[0];
        byArray5[en.lIIII[5]] = lIIII[50];
        byArray5[en.lIIII[7]] = lIIII[0];
        byArray5[en.lIIII[8]] = lIIII[38];
        byArray5[en.lIIII[10]] = lIIII[0];
        byArray5[en.lIIII[11]] = lIIII[15];
        byArray5[en.lIIII[13]] = lIIII[0];
        byArray5[en.lIIII[14]] = lIIII[9];
        byArray5[en.lIIII[16]] = lIIII[0];
        byArray5[en.lIIII[17]] = lIIII[12];
        byArray5[en.lIIII[19]] = lIIII[0];
        byArray5[en.lIIII[20]] = lIIII[15];
        byArray5[en.lIIII[22]] = lIIII[0];
        byArray5[en.lIIII[23]] = lIIII[18];
        byArray5[en.lIIII[24]] = lIIII[0];
        byArray5[en.lIIII[25]] = lIIII[21];
        byArray5[en.lIIII[27]] = lIIII[0];
        byArray5[en.lIIII[28]] = lIIII[9];
        byArray5[en.lIIII[29]] = lIIII[0];
        byArray5[en.lIIII[30]] = lIIII[51];
        byArray5[en.lIIII[31]] = lIIII[0];
        byArray5[en.lIIII[32]] = lIIII[26];
        byArray5[en.lIIII[33]] = lIIII[0];
        byArray5[en.lIIII[34]] = lIIII[9];
        byArray5[en.lIIII[36]] = lIIII[0];
        byArray5[en.lIIII[37]] = lIIII[52];
        byArray5[en.lIIII[39]] = lIIII[0];
        byArray5[en.lIIII[40]] = lIIII[15];
        byArray5[en.lIIII[1]] = lIIII[0];
        byArray5[en.lIIII[53]] = lIIII[48];
        byArray5[en.lIIII[9]] = lIIII[0];
        byArray5[en.lIIII[54]] = lIIII[55];
        byArray5[en.lIIII[56]] = lIIII[0];
        byArray5[en.lIIII[57]] = lIIII[44];
        byArray5[en.lIIII[58]] = lIIII[1];
        byArray5[en.lIIII[59]] = lIIII[45];
        byArray5[en.lIIII[60]] = lIIII[0];
        byArray5[en.lIIII[61]] = lIIII[12];
        byArray5[en.lIIII[55]] = lIIII[0];
        byArray5[en.lIIII[62]] = lIIII[9];
        byArray5[en.lIIII[63]] = lIIII[0];
        byArray5[en.lIIII[64]] = lIIII[12];
        byArray5[en.lIIII[65]] = lIIII[0];
        byArray5[en.lIIII[66]] = lIIII[15];
        byArray5[en.lIIII[67]] = lIIII[0];
        byArray5[en.lIIII[68]] = lIIII[69];
        byArray5[en.lIIII[70]] = lIIII[0];
        byArray5[en.lIIII[71]] = lIIII[9];
        byArray5[en.lIIII[72]] = lIIII[0];
        byArray5[en.lIIII[73]] = lIIII[74];
        byArray5[en.lIIII[75]] = lIIII[0];
        byArray5[en.lIIII[76]] = lIIII[77];
        byArray5[en.lIIII[78]] = lIIII[0];
        byArray5[en.lIIII[79]] = lIIII[35];
        byArray5[en.lIIII[80]] = lIIII[0];
        byArray5[en.lIIII[81]] = lIIII[9];
        byArray5[en.lIIII[82]] = lIIII[0];
        byArray5[en.lIIII[83]] = lIIII[52];
        byArray5[en.lIIII[84]] = lIIII[0];
        byArray5[en.lIIII[85]] = lIIII[15];
        byArray5[en.lIIII[86]] = lIIII[0];
        byArray5[en.lIIII[87]] = lIIII[48];
        byArray5[en.lIIII[88]] = lIIII[0];
        byArray5[en.lIIII[89]] = lIIII[9];
        byArray5[en.lIIII[42]] = lIIII[0];
        byArray5[en.lIIII[90]] = lIIII[48];
        byArray5[en.lIIII[91]] = lIIII[0];
        byArray5[en.lIIII[92]] = lIIII[6];
        byArray5[en.lIIII[93]] = lIIII[0];
        byArray5[en.lIIII[94]] = lIIII[62];
        String[] stringArray2 = new String[lIIII[4]];
        byte[] byArray6 = new byte[lIIII[10]];
        byArray6[en.lIIII[0]] = lIIII[0];
        byArray6[en.lIIII[2]] = lIIII[42];
        byArray6[en.lIIII[4]] = lIIII[1];
        byArray6[en.lIIII[5]] = lIIII[43];
        byArray6[en.lIIII[7]] = lIIII[0];
        byArray6[en.lIIII[8]] = lIIII[12];
        stringArray2[en.lIIII[0]] = ec.a(byArray6);
        byte[] byArray7 = new byte[lIIII[10]];
        byArray7[en.lIIII[0]] = lIIII[0];
        byArray7[en.lIIII[2]] = lIIII[44];
        byArray7[en.lIIII[4]] = lIIII[1];
        byArray7[en.lIIII[5]] = lIIII[45];
        byArray7[en.lIIII[7]] = lIIII[0];
        byArray7[en.lIIII[8]] = lIIII[12];
        stringArray2[en.lIIII[2]] = ec.a(byArray7);
        this.o = new ChoiceGroup(ec.a(byArray5), lIIII[2], stringArray2, null);
        this.append((Item)this.o);
        byte[] byArray8 = new byte[lIIII[19]];
        byArray8[en.lIIII[0]] = lIIII[0];
        byArray8[en.lIIII[2]] = lIIII[95];
        byArray8[en.lIIII[4]] = lIIII[0];
        byArray8[en.lIIII[5]] = lIIII[15];
        byArray8[en.lIIII[7]] = lIIII[0];
        byArray8[en.lIIII[8]] = lIIII[48];
        byArray8[en.lIIII[10]] = lIIII[0];
        byArray8[en.lIIII[11]] = lIIII[9];
        byArray8[en.lIIII[13]] = lIIII[0];
        byArray8[en.lIIII[14]] = lIIII[48];
        byArray8[en.lIIII[16]] = lIIII[0];
        byArray8[en.lIIII[17]] = lIIII[6];
        this.i = new TextField(ec.a(byArray8), String.valueOf(b), lIIII[14], lIIII[4]);
        this.append((Item)this.i);
        byte[] byArray9 = new byte[lIIII[38]];
        byArray9[en.lIIII[0]] = lIIII[0];
        byArray9[en.lIIII[2]] = lIIII[91];
        byArray9[en.lIIII[4]] = lIIII[0];
        byArray9[en.lIIII[5]] = lIIII[67];
        byArray9[en.lIIII[7]] = lIIII[0];
        byArray9[en.lIIII[8]] = lIIII[26];
        byArray9[en.lIIII[10]] = lIIII[0];
        byArray9[en.lIIII[11]] = lIIII[9];
        byArray9[en.lIIII[13]] = lIIII[2];
        byArray9[en.lIIII[14]] = lIIII[25];
        byArray9[en.lIIII[16]] = lIIII[0];
        byArray9[en.lIIII[17]] = lIIII[50];
        byArray9[en.lIIII[19]] = lIIII[0];
        byArray9[en.lIIII[20]] = lIIII[38];
        byArray9[en.lIIII[22]] = lIIII[0];
        byArray9[en.lIIII[23]] = lIIII[15];
        byArray9[en.lIIII[24]] = lIIII[0];
        byArray9[en.lIIII[25]] = lIIII[9];
        byArray9[en.lIIII[27]] = lIIII[0];
        byArray9[en.lIIII[28]] = lIIII[74];
        byArray9[en.lIIII[29]] = lIIII[0];
        byArray9[en.lIIII[30]] = lIIII[15];
        byArray9[en.lIIII[31]] = lIIII[0];
        byArray9[en.lIIII[32]] = lIIII[48];
        byArray9[en.lIIII[33]] = lIIII[0];
        byArray9[en.lIIII[34]] = lIIII[96];
        byArray9[en.lIIII[36]] = lIIII[1];
        byArray9[en.lIIII[37]] = lIIII[97];
        byArray9[en.lIIII[39]] = lIIII[0];
        byArray9[en.lIIII[40]] = lIIII[38];
        byArray9[en.lIIII[1]] = lIIII[0];
        byArray9[en.lIIII[53]] = lIIII[9];
        byArray9[en.lIIII[9]] = lIIII[0];
        byArray9[en.lIIII[54]] = lIIII[52];
        byArray9[en.lIIII[56]] = lIIII[0];
        byArray9[en.lIIII[57]] = lIIII[15];
        byArray9[en.lIIII[58]] = lIIII[0];
        byArray9[en.lIIII[59]] = lIIII[48];
        byArray9[en.lIIII[60]] = lIIII[0];
        byArray9[en.lIIII[61]] = lIIII[55];
        byArray9[en.lIIII[55]] = lIIII[0];
        byArray9[en.lIIII[62]] = lIIII[74];
        byArray9[en.lIIII[63]] = lIIII[0];
        byArray9[en.lIIII[64]] = lIIII[50];
        byArray9[en.lIIII[65]] = lIIII[0];
        byArray9[en.lIIII[66]] = lIIII[74];
        byArray9[en.lIIII[67]] = lIIII[0];
        byArray9[en.lIIII[68]] = lIIII[15];
        byArray9[en.lIIII[70]] = lIIII[0];
        byArray9[en.lIIII[71]] = lIIII[9];
        byArray9[en.lIIII[72]] = lIIII[0];
        byArray9[en.lIIII[73]] = lIIII[38];
        byArray9[en.lIIII[75]] = lIIII[0];
        byArray9[en.lIIII[76]] = lIIII[15];
        byArray9[en.lIIII[78]] = lIIII[0];
        byArray9[en.lIIII[79]] = lIIII[47];
        byArray9[en.lIIII[80]] = lIIII[0];
        byArray9[en.lIIII[81]] = lIIII[48];
        byArray9[en.lIIII[82]] = lIIII[0];
        byArray9[en.lIIII[83]] = lIIII[9];
        byArray9[en.lIIII[84]] = lIIII[0];
        byArray9[en.lIIII[85]] = lIIII[71];
        byArray9[en.lIIII[86]] = lIIII[0];
        byArray9[en.lIIII[87]] = lIIII[9];
        byArray9[en.lIIII[88]] = lIIII[0];
        byArray9[en.lIIII[89]] = lIIII[52];
        byArray9[en.lIIII[42]] = lIIII[0];
        byArray9[en.lIIII[90]] = lIIII[15];
        byArray9[en.lIIII[91]] = lIIII[0];
        byArray9[en.lIIII[92]] = lIIII[21];
        byArray9[en.lIIII[93]] = lIIII[1];
        byArray9[en.lIIII[94]] = lIIII[98];
        byArray9[en.lIIII[49]] = lIIII[0];
        byArray9[en.lIIII[99]] = lIIII[38];
        byArray9[en.lIIII[100]] = lIIII[0];
        byArray9[en.lIIII[95]] = lIIII[41];
        byArray9[en.lIIII[101]] = lIIII[0];
        byArray9[en.lIIII[46]] = lIIII[9];
        byArray9[en.lIIII[102]] = lIIII[0];
        byArray9[en.lIIII[103]] = lIIII[12];
        byArray9[en.lIIII[104]] = lIIII[0];
        byArray9[en.lIIII[105]] = lIIII[106];
        byArray9[en.lIIII[107]] = lIIII[1];
        byArray9[en.lIIII[108]] = lIIII[45];
        byArray9[en.lIIII[44]] = lIIII[0];
        byArray9[en.lIIII[3]] = lIIII[38];
        byArray9[en.lIIII[109]] = lIIII[0];
        byArray9[en.lIIII[110]] = lIIII[41];
        byArray9[en.lIIII[111]] = lIIII[0];
        byArray9[en.lIIII[112]] = lIIII[55];
        byArray9[en.lIIII[113]] = lIIII[0];
        byArray9[en.lIIII[114]] = lIIII[51];
        byArray9[en.lIIII[115]] = lIIII[1];
        byArray9[en.lIIII[116]] = lIIII[117];
        byArray9[en.lIIII[118]] = lIIII[0];
        byArray9[en.lIIII[119]] = lIIII[48];
        byArray9[en.lIIII[120]] = lIIII[0];
        byArray9[en.lIIII[47]] = lIIII[9];
        byArray9[en.lIIII[121]] = lIIII[0];
        byArray9[en.lIIII[74]] = lIIII[74];
        byArray9[en.lIIII[51]] = lIIII[0];
        byArray9[en.lIIII[18]] = lIIII[50];
        byArray9[en.lIIII[122]] = lIIII[0];
        byArray9[en.lIIII[41]] = lIIII[74];
        byArray9[en.lIIII[15]] = lIIII[0];
        byArray9[en.lIIII[35]] = lIIII[15];
        byArray9[en.lIIII[123]] = lIIII[0];
        byArray9[en.lIIII[52]] = lIIII[62];
        byArray9[en.lIIII[124]] = lIIII[0];
        byArray9[en.lIIII[125]] = lIIII[62];
        this.j = new TextField(ec.a(byArray9), String.valueOf(l), lIIII[126], lIIII[0]);
        this.append((Item)this.j);
        byte[] byArray10 = new byte[lIIII[91]];
        byArray10[en.lIIII[0]] = lIIII[0];
        byArray10[en.lIIII[2]] = lIIII[99];
        byArray10[en.lIIII[4]] = lIIII[0];
        byArray10[en.lIIII[5]] = lIIII[91];
        byArray10[en.lIIII[7]] = lIIII[0];
        byArray10[en.lIIII[8]] = lIIII[9];
        byArray10[en.lIIII[10]] = lIIII[0];
        byArray10[en.lIIII[11]] = lIIII[127];
        byArray10[en.lIIII[13]] = lIIII[0];
        byArray10[en.lIIII[14]] = lIIII[48];
        byArray10[en.lIIII[16]] = lIIII[0];
        byArray10[en.lIIII[17]] = lIIII[50];
        byArray10[en.lIIII[19]] = lIIII[0];
        byArray10[en.lIIII[20]] = lIIII[35];
        byArray10[en.lIIII[22]] = lIIII[0];
        byArray10[en.lIIII[23]] = lIIII[9];
        byArray10[en.lIIII[24]] = lIIII[0];
        byArray10[en.lIIII[25]] = lIIII[125];
        byArray10[en.lIIII[27]] = lIIII[0];
        byArray10[en.lIIII[28]] = lIIII[48];
        byArray10[en.lIIII[29]] = lIIII[1];
        byArray10[en.lIIII[30]] = lIIII[128];
        byArray10[en.lIIII[31]] = lIIII[0];
        byArray10[en.lIIII[32]] = lIIII[38];
        byArray10[en.lIIII[33]] = lIIII[0];
        byArray10[en.lIIII[34]] = lIIII[9];
        byArray10[en.lIIII[36]] = lIIII[2];
        byArray10[en.lIIII[37]] = lIIII[25];
        byArray10[en.lIIII[39]] = lIIII[0];
        byArray10[en.lIIII[40]] = lIIII[50];
        byArray10[en.lIIII[1]] = lIIII[0];
        byArray10[en.lIIII[53]] = lIIII[38];
        byArray10[en.lIIII[9]] = lIIII[0];
        byArray10[en.lIIII[54]] = lIIII[15];
        byArray10[en.lIIII[56]] = lIIII[0];
        byArray10[en.lIIII[57]] = lIIII[65];
        byArray10[en.lIIII[58]] = lIIII[0];
        byArray10[en.lIIII[59]] = lIIII[9];
        byArray10[en.lIIII[60]] = lIIII[0];
        byArray10[en.lIIII[61]] = lIIII[74];
        byArray10[en.lIIII[55]] = lIIII[0];
        byArray10[en.lIIII[62]] = lIIII[50];
        byArray10[en.lIIII[63]] = lIIII[0];
        byArray10[en.lIIII[64]] = lIIII[74];
        byArray10[en.lIIII[65]] = lIIII[0];
        byArray10[en.lIIII[66]] = lIIII[15];
        byArray10[en.lIIII[67]] = lIIII[0];
        byArray10[en.lIIII[68]] = lIIII[9];
        byArray10[en.lIIII[70]] = lIIII[0];
        byArray10[en.lIIII[71]] = lIIII[38];
        byArray10[en.lIIII[72]] = lIIII[0];
        byArray10[en.lIIII[73]] = lIIII[15];
        byArray10[en.lIIII[75]] = lIIII[0];
        byArray10[en.lIIII[76]] = lIIII[47];
        byArray10[en.lIIII[78]] = lIIII[0];
        byArray10[en.lIIII[79]] = lIIII[48];
        byArray10[en.lIIII[80]] = lIIII[0];
        byArray10[en.lIIII[81]] = lIIII[9];
        byArray10[en.lIIII[82]] = lIIII[0];
        byArray10[en.lIIII[83]] = lIIII[51];
        byArray10[en.lIIII[84]] = lIIII[1];
        byArray10[en.lIIII[85]] = lIIII[117];
        byArray10[en.lIIII[86]] = lIIII[0];
        byArray10[en.lIIII[87]] = lIIII[48];
        byArray10[en.lIIII[88]] = lIIII[0];
        byArray10[en.lIIII[89]] = lIIII[9];
        byArray10[en.lIIII[42]] = lIIII[0];
        byArray10[en.lIIII[90]] = lIIII[65];
        this.k = new TextField(ec.a(byArray10), String.valueOf(m), lIIII[126], lIIII[0]);
        this.append((Item)this.k);
        byte[] byArray11 = new byte[lIIII[27]];
        byArray11[en.lIIII[0]] = lIIII[0];
        byArray11[en.lIIII[2]] = lIIII[105];
        byArray11[en.lIIII[4]] = lIIII[0];
        byArray11[en.lIIII[5]] = lIIII[48];
        byArray11[en.lIIII[7]] = lIIII[1];
        byArray11[en.lIIII[8]] = lIIII[129];
        byArray11[en.lIIII[10]] = lIIII[0];
        byArray11[en.lIIII[11]] = lIIII[12];
        byArray11[en.lIIII[13]] = lIIII[0];
        byArray11[en.lIIII[14]] = lIIII[9];
        byArray11[en.lIIII[16]] = lIIII[0];
        byArray11[en.lIIII[17]] = lIIII[121];
        byArray11[en.lIIII[19]] = lIIII[0];
        byArray11[en.lIIII[20]] = lIIII[48];
        byArray11[en.lIIII[22]] = lIIII[0];
        byArray11[en.lIIII[23]] = lIIII[122];
        byArray11[en.lIIII[24]] = lIIII[0];
        byArray11[en.lIIII[25]] = lIIII[122];
        String[] stringArray3 = new String[lIIII[4]];
        byte[] byArray12 = new byte[lIIII[10]];
        byArray12[en.lIIII[0]] = lIIII[0];
        byArray12[en.lIIII[2]] = lIIII[42];
        byArray12[en.lIIII[4]] = lIIII[1];
        byArray12[en.lIIII[5]] = lIIII[43];
        byArray12[en.lIIII[7]] = lIIII[0];
        byArray12[en.lIIII[8]] = lIIII[12];
        stringArray3[en.lIIII[0]] = ec.a(byArray12);
        byte[] byArray13 = new byte[lIIII[10]];
        byArray13[en.lIIII[0]] = lIIII[0];
        byArray13[en.lIIII[2]] = lIIII[44];
        byArray13[en.lIIII[4]] = lIIII[1];
        byArray13[en.lIIII[5]] = lIIII[45];
        byArray13[en.lIIII[7]] = lIIII[0];
        byArray13[en.lIIII[8]] = lIIII[12];
        stringArray3[en.lIIII[2]] = ec.a(byArray13);
        this.q = new ChoiceGroup(ec.a(byArray11), lIIII[2], stringArray3, null);
        this.append((Item)this.q);
        byte[] byArray14 = new byte[lIIII[10]];
        byArray14[en.lIIII[0]] = lIIII[0];
        byArray14[en.lIIII[2]] = lIIII[101];
        byArray14[en.lIIII[4]] = lIIII[2];
        byArray14[en.lIIII[5]] = lIIII[130];
        byArray14[en.lIIII[7]] = lIIII[0];
        byArray14[en.lIIII[8]] = lIIII[48];
        this.n = new Command(ec.a(byArray14), lIIII[7], lIIII[0]);
        this.addCommand(this.n);
        byte[] byArray15 = new byte[lIIII[16]];
        byArray15[en.lIIII[0]] = lIIII[0];
        byArray15[en.lIIII[2]] = lIIII[44];
        byArray15[en.lIIII[4]] = lIIII[0];
        byArray15[en.lIIII[5]] = lIIII[15];
        byArray15[en.lIIII[7]] = lIIII[0];
        byArray15[en.lIIII[8]] = lIIII[21];
        byArray15[en.lIIII[10]] = lIIII[0];
        byArray15[en.lIIII[11]] = lIIII[50];
        byArray15[en.lIIII[13]] = lIIII[0];
        byArray15[en.lIIII[14]] = lIIII[12];
        this.addCommand(new Command(ec.a(byArray15), lIIII[11], lIIII[0]));
        this.setCommandListener(this);
        this.p.setSelectedIndex(e ? lIIII[0] : lIIII[2], lIIII[2]);
        llllllIllIlIllI.o.setSelectedIndex(f ? lIIII[0] : lIIII[2], lIIII[2]);
        llllllIllIlIllI.q.setSelectedIndex(g ? lIIII[0] : lIIII[2], lIIII[2]);
    }

    public static void a() {
        byte[] byArray = new byte[lIIII[29]];
        byArray[en.lIIII[0]] = lIIII[0];
        byArray[en.lIIII[2]] = lIIII[90];
        byArray[en.lIIII[4]] = lIIII[0];
        byArray[en.lIIII[5]] = lIIII[77];
        byArray[en.lIIII[7]] = lIIII[0];
        byArray[en.lIIII[8]] = lIIII[35];
        byArray[en.lIIII[10]] = lIIII[0];
        byArray[en.lIIII[11]] = lIIII[9];
        byArray[en.lIIII[13]] = lIIII[2];
        byArray[en.lIIII[14]] = lIIII[25];
        byArray[en.lIIII[16]] = lIIII[1];
        byArray[en.lIIII[17]] = lIIII[131];
        byArray[en.lIIII[19]] = lIIII[0];
        byArray[en.lIIII[20]] = lIIII[12];
        byArray[en.lIIII[22]] = lIIII[0];
        byArray[en.lIIII[23]] = lIIII[9];
        byArray[en.lIIII[24]] = lIIII[0];
        byArray[en.lIIII[25]] = lIIII[48];
        byArray[en.lIIII[27]] = lIIII[0];
        byArray[en.lIIII[28]] = lIIII[6];
        Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)new en(ec.a(byArray)));
    }

    /*
     * WARNING - void declaration
     */
    public static void b() {
        byte[] byArray = new byte[lIIII[27]];
        byArray[en.lIIII[0]] = lIIII[0];
        byArray[en.lIIII[2]] = lIIII[48];
        byArray[en.lIIII[4]] = lIIII[0];
        byArray[en.lIIII[5]] = lIIII[6];
        byArray[en.lIIII[7]] = lIIII[0];
        byArray[en.lIIII[8]] = lIIII[108];
        byArray[en.lIIII[10]] = lIIII[0];
        byArray[en.lIIII[11]] = lIIII[18];
        byArray[en.lIIII[13]] = lIIII[0];
        byArray[en.lIIII[14]] = lIIII[12];
        byArray[en.lIIII[16]] = lIIII[0];
        byArray[en.lIIII[17]] = lIIII[12];
        byArray[en.lIIII[19]] = lIIII[0];
        byArray[en.lIIII[20]] = lIIII[35];
        byArray[en.lIIII[22]] = lIIII[0];
        byArray[en.lIIII[23]] = lIIII[38];
        byArray[en.lIIII[24]] = lIIII[0];
        byArray[en.lIIII[25]] = lIIII[41];
        byte[] byArray2 = dv.a(ec.a(byArray));
        if (byArray2 != null) {
            ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(byArray2);
            DataInputStream llllllIllIIIIll = new DataInputStream(byteArrayInputStream);
            try {
                void llllllIllIIIlIl;
                a = llllllIllIIIIll.readInt();
                b = llllllIllIIIIll.readInt();
                l = llllllIllIIIIll.readUTF();
                m = llllllIllIIIIll.readUTF();
                e = llllllIllIIIIll.readBoolean();
                f = llllllIllIIIIll.readBoolean();
                g = llllllIllIIIIll.readBoolean();
                if (f) {
                    at.d = lIIII[2];
                    v.cr = lIIII[2];
                    at.g(l);
                }
                byte[] byArray3 = new byte[lIIII[7]];
                byArray3[en.lIIII[0]] = lIIII[0];
                byArray3[en.lIIII[2]] = lIIII[66];
                byArray3[en.lIIII[4]] = lIIII[0];
                byArray3[en.lIIII[5]] = lIIII[71];
                if (!m.equals(ec.a(byArray3))) {
                    byte[] byArray4 = new byte[lIIII[4]];
                    byArray4[en.lIIII[0]] = lIIII[0];
                    byArray4[en.lIIII[2]] = lIIII[65];
                    String[] llllllIllIIIIIl = at.a(m, ec.a(byArray4));
                    d = new dh();
                    int llllllIlIllllll = lIIII[0];
                    while (llllllIlIllllll < llllllIllIIIIIl.length) {
                        d.addElement(new Integer(llllllIllIIIIIl[llllllIlIllllll].trim()));
                        ++llllllIlIllllll;
                    }
                }
                llllllIllIIIIll.close();
                llllllIllIIIlIl.close();
            }
            catch (Exception exception) {
                // empty catch block
            }
        }
    }

    /*
     * WARNING - void declaration
     */
    public void commandAction(Command command, Displayable displayable) {
        if (command == this.n) {
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            DataOutputStream llllllIlIlIIlll = new DataOutputStream(byteArrayOutputStream);
            try {
                void llllllIlIlIlIIl;
                en llllllIlIlIllIl;
                a = Integer.parseInt(llllllIlIlIllIl.h.getString());
                b = Integer.parseInt(llllllIlIlIllIl.i.getString());
                l = llllllIlIlIllIl.j.getString();
                m = llllllIlIlIllIl.k.getString();
                e = llllllIlIlIllIl.p.getSelectedIndex() == 0 ? lIIII[2] : lIIII[0];
                f = llllllIlIlIllIl.o.getSelectedIndex() == 0 ? lIIII[2] : lIIII[0];
                g = llllllIlIlIllIl.q.getSelectedIndex() == 0 ? lIIII[2] : lIIII[0];
                int n2 = g ? 1 : 0;
                if (f) {
                    at.d = lIIII[2];
                    v.cr = lIIII[2];
                    at.g(l);
                }
                byte[] byArray = new byte[lIIII[7]];
                byArray[en.lIIII[0]] = lIIII[0];
                byArray[en.lIIII[2]] = lIIII[66];
                byArray[en.lIIII[4]] = lIIII[0];
                byArray[en.lIIII[5]] = lIIII[71];
                if (!m.equals(ec.a(byArray))) {
                    byte[] byArray2 = new byte[lIIII[4]];
                    byArray2[en.lIIII[0]] = lIIII[0];
                    byArray2[en.lIIII[2]] = lIIII[65];
                    String[] llllllIlIlIIllI = at.a(m, ec.a(byArray2));
                    d = new dh();
                    int llllllIlIlIIlII = lIIII[0];
                    while (llllllIlIlIIlII < llllllIlIlIIllI.length) {
                        d.addElement(new Integer(llllllIlIlIIllI[llllllIlIlIIlII].trim()));
                        ++llllllIlIlIIlII;
                    }
                }
                llllllIlIlIIlll.writeInt(a);
                llllllIlIlIIlll.writeInt(b);
                llllllIlIlIIlll.writeUTF(l);
                llllllIlIlIIlll.writeUTF(m);
                llllllIlIlIIlll.writeBoolean(e);
                llllllIlIlIIlll.writeBoolean(f);
                llllllIlIlIIlll.writeBoolean(g);
                byte[] byArray3 = new byte[lIIII[27]];
                byArray3[en.lIIII[0]] = lIIII[0];
                byArray3[en.lIIII[2]] = lIIII[48];
                byArray3[en.lIIII[4]] = lIIII[0];
                byArray3[en.lIIII[5]] = lIIII[6];
                byArray3[en.lIIII[7]] = lIIII[0];
                byArray3[en.lIIII[8]] = lIIII[108];
                byArray3[en.lIIII[10]] = lIIII[0];
                byArray3[en.lIIII[11]] = lIIII[18];
                byArray3[en.lIIII[13]] = lIIII[0];
                byArray3[en.lIIII[14]] = lIIII[12];
                byArray3[en.lIIII[16]] = lIIII[0];
                byArray3[en.lIIII[17]] = lIIII[12];
                byArray3[en.lIIII[19]] = lIIII[0];
                byArray3[en.lIIII[20]] = lIIII[35];
                byArray3[en.lIIII[22]] = lIIII[0];
                byArray3[en.lIIII[23]] = lIIII[38];
                byArray3[en.lIIII[24]] = lIIII[0];
                byArray3[en.lIIII[25]] = lIIII[41];
                dv.a(ec.a(byArray3), ((ByteArrayOutputStream)llllllIlIlIlIIl).toByteArray());
                llllllIlIlIIlll.flush();
                llllllIlIlIlIIl.flush();
                byte[] byArray4 = new byte[lIIII[65]];
                byArray4[en.lIIII[0]] = lIIII[0];
                byArray4[en.lIIII[2]] = lIIII[101];
                byArray4[en.lIIII[4]] = lIIII[2];
                byArray4[en.lIIII[5]] = lIIII[130];
                byArray4[en.lIIII[7]] = lIIII[0];
                byArray4[en.lIIII[8]] = lIIII[48];
                byArray4[en.lIIII[10]] = lIIII[0];
                byArray4[en.lIIII[11]] = lIIII[9];
                byArray4[en.lIIII[13]] = lIIII[0];
                byArray4[en.lIIII[14]] = lIIII[74];
                byArray4[en.lIIII[16]] = lIIII[0];
                byArray4[en.lIIII[17]] = lIIII[77];
                byArray4[en.lIIII[19]] = lIIII[0];
                byArray4[en.lIIII[20]] = lIIII[35];
                byArray4[en.lIIII[22]] = lIIII[0];
                byArray4[en.lIIII[23]] = lIIII[9];
                byArray4[en.lIIII[24]] = lIIII[2];
                byArray4[en.lIIII[25]] = lIIII[25];
                byArray4[en.lIIII[27]] = lIIII[1];
                byArray4[en.lIIII[28]] = lIIII[131];
                byArray4[en.lIIII[29]] = lIIII[0];
                byArray4[en.lIIII[30]] = lIIII[12];
                byArray4[en.lIIII[31]] = lIIII[0];
                byArray4[en.lIIII[32]] = lIIII[9];
                byArray4[en.lIIII[33]] = lIIII[0];
                byArray4[en.lIIII[34]] = lIIII[12];
                byArray4[en.lIIII[36]] = lIIII[0];
                byArray4[en.lIIII[37]] = lIIII[15];
                byArray4[en.lIIII[39]] = lIIII[0];
                byArray4[en.lIIII[40]] = lIIII[77];
                byArray4[en.lIIII[1]] = lIIII[0];
                byArray4[en.lIIII[53]] = lIIII[38];
                byArray4[en.lIIII[9]] = lIIII[0];
                byArray4[en.lIIII[54]] = lIIII[15];
                byArray4[en.lIIII[56]] = lIIII[0];
                byArray4[en.lIIII[57]] = lIIII[9];
                byArray4[en.lIIII[58]] = lIIII[0];
                byArray4[en.lIIII[59]] = lIIII[74];
                byArray4[en.lIIII[60]] = lIIII[0];
                byArray4[en.lIIII[61]] = lIIII[132];
                byArray4[en.lIIII[55]] = lIIII[0];
                byArray4[en.lIIII[62]] = lIIII[38];
                byArray4[en.lIIII[63]] = lIIII[0];
                byArray4[en.lIIII[64]] = lIIII[41];
                at.a(ec.a(byArray4));
            }
            catch (Exception llllllIlIlIIllI) {
                // empty catch block
            }
        }
        Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)dc.a);
    }

    private static void lIIIl() {
        lIIII = new int[133];
        en.lIIII[0] = (0x8C ^ 0xA3) << " ".length() & ~((0x15 ^ 0x3A) << " ".length());
        en.lIIII[1] = (0x66 ^ 0x69) << " ".length();
        en.lIIII[2] = " ".length();
        en.lIIII[3] = 0xF6 ^ 0xA3;
        en.lIIII[4] = " ".length() << " ".length();
        en.lIIII[5] = "   ".length();
        en.lIIII[6] = (0xA0 ^ 0xA7) << (" ".length() << (" ".length() << " ".length()));
        en.lIIII[7] = " ".length() << (" ".length() << " ".length());
        en.lIIII[8] = 0x71 ^ 0x74;
        en.lIIII[9] = " ".length() << (0xC6 ^ 0xC3);
        en.lIIII[10] = "   ".length() << " ".length();
        en.lIIII[11] = 3 ^ 4;
        en.lIIII[12] = (0x82 ^ 0x9F) << (" ".length() << " ".length());
        en.lIIII[13] = " ".length() << "   ".length();
        en.lIIII[14] = 0xB8 ^ 0xB1;
        en.lIIII[15] = (0x8A ^ 0x87) << "   ".length();
        en.lIIII[16] = (0x7A ^ 0x7F) << " ".length();
        en.lIIII[17] = 0x6D ^ 0x66;
        en.lIIII[18] = 0xA4 ^ 0xC1;
        en.lIIII[19] = "   ".length() << (" ".length() << " ".length());
        en.lIIII[20] = 0x9A ^ 0x97;
        en.lIIII[21] = 0xEA ^ 0x85;
        en.lIIII[22] = (0x72 ^ 0x75) << " ".length();
        en.lIIII[23] = 0x75 ^ 0x7A;
        en.lIIII[24] = " ".length() << (" ".length() << (" ".length() << " ".length()));
        en.lIIII[25] = 0x96 ^ 0x87;
        en.lIIII[26] = 0x44 ^ 0x37;
        en.lIIII[27] = (0xA6 ^ 0xAF) << " ".length();
        en.lIIII[28] = 0x66 ^ 0x75;
        en.lIIII[29] = (0x76 ^ 0x73) << (" ".length() << " ".length());
        en.lIIII[30] = 0x64 ^ 0x71;
        en.lIIII[31] = (0x23 ^ 0x28) << " ".length();
        en.lIIII[32] = 0xBC ^ 0xAB;
        en.lIIII[33] = "   ".length() << "   ".length();
        en.lIIII[34] = 0x92 ^ 0x8B;
        en.lIIII[35] = 0x57 ^ 0x3E;
        en.lIIII[36] = (0xC8 ^ 0xC5) << " ".length();
        en.lIIII[37] = 0xAE ^ 0xB5;
        en.lIIII[38] = (0xAB ^ 0x9C) << " ".length();
        en.lIIII[39] = (0x24 ^ 0x23) << (" ".length() << " ".length());
        en.lIIII[40] = 0x27 ^ 0x3A;
        en.lIIII[41] = 0x5C ^ 0x3B;
        en.lIIII[42] = (0x78 ^ 0x59) << " ".length();
        en.lIIII[43] = -(0xF9 ^ 0xAA);
        en.lIIII[44] = (0xB0 ^ 0xA5) << (" ".length() << " ".length());
        en.lIIII[45] = -(0xC1 ^ 0x90);
        en.lIIII[46] = 0xF9 ^ 0xB4;
        en.lIIII[47] = 0x2C ^ 0x4D;
        en.lIIII[48] = 0x7F ^ 0xA;
        en.lIIII[49] = (0x57 ^ 0x5E) << "   ".length();
        en.lIIII[50] = -(0xDB ^ 0xC4);
        en.lIIII[51] = (0x16 ^ 0xF) << (" ".length() << " ".length());
        en.lIIII[52] = 0x44 ^ 0x2F;
        en.lIIII[53] = 7 ^ 0x18;
        en.lIIII[54] = 0x51 ^ 0x70;
        en.lIIII[55] = (0x91 ^ 0x94) << "   ".length();
        en.lIIII[56] = (0x5F ^ 0x4E) << " ".length();
        en.lIIII[57] = 6 ^ 0x25;
        en.lIIII[58] = (0x18 ^ 0x11) << (" ".length() << " ".length());
        en.lIIII[59] = 0x3E ^ 0x1B;
        en.lIIII[60] = (0xA2 ^ 0xB1) << " ".length();
        en.lIIII[61] = 0x22 ^ 5;
        en.lIIII[62] = 0x74 ^ 0x5D;
        en.lIIII[63] = (0x96 ^ 0x83) << " ".length();
        en.lIIII[64] = 0xBE ^ 0x95;
        en.lIIII[65] = (0x5E ^ 0x55) << (" ".length() << " ".length());
        en.lIIII[66] = 0x49 ^ 0x64;
        en.lIIII[67] = (0x48 ^ 0x5F) << " ".length();
        en.lIIII[68] = 7 ^ 0x28;
        en.lIIII[69] = -(0x6A ^ 0x7E);
        en.lIIII[70] = "   ".length() << (" ".length() << (" ".length() << " ".length()));
        en.lIIII[71] = 0x74 ^ 0x45;
        en.lIIII[72] = (0xA0 ^ 0xB9) << " ".length();
        en.lIIII[73] = 0x76 ^ 0x45;
        en.lIIII[74] = 0x47 ^ 0x24;
        en.lIIII[75] = (0x46 ^ 0x4B) << (" ".length() << " ".length());
        en.lIIII[76] = 8 ^ 0x3D;
        en.lIIII[77] = -(0x9D ^ 0xBD);
        en.lIIII[78] = (0x3C ^ 0x27) << " ".length();
        en.lIIII[79] = 0xF0 ^ 0xC7;
        en.lIIII[80] = (0x49 ^ 0x4E) << "   ".length();
        en.lIIII[81] = 0x3F ^ 6;
        en.lIIII[82] = (0x15 ^ 8) << " ".length();
        en.lIIII[83] = 0xB3 ^ 0x88;
        en.lIIII[84] = (0xAC ^ 0xA3) << (" ".length() << " ".length());
        en.lIIII[85] = 0x2A ^ 0x17;
        en.lIIII[86] = (0x9A ^ 0x85) << " ".length();
        en.lIIII[87] = 0xB1 ^ 0x8E;
        en.lIIII[88] = " ".length() << ("   ".length() << " ".length());
        en.lIIII[89] = 0x25 ^ 0x64;
        en.lIIII[90] = 0xB ^ 0x48;
        en.lIIII[91] = (8 ^ 0x19) << (" ".length() << " ".length());
        en.lIIII[92] = 0xFB ^ 0xBE;
        en.lIIII[93] = (0x18 ^ 0x3B) << " ".length();
        en.lIIII[94] = 0x62 ^ 0x25;
        en.lIIII[95] = 0xF4 ^ 0xBF;
        en.lIIII[96] = 0x34 ^ 0x4D;
        en.lIIII[97] = -(0x2E ^ 0x13);
        en.lIIII[98] = -(0x2D ^ 0x70);
        en.lIIII[99] = 0x74 ^ 0x3D;
        en.lIIII[100] = (0x1C ^ 0x39) << " ".length();
        en.lIIII[101] = (0x9E ^ 0x8D) << (" ".length() << " ".length());
        en.lIIII[102] = (0x16 ^ 0x31) << " ".length();
        en.lIIII[103] = 0xFC ^ 0xB3;
        en.lIIII[104] = (0x7A ^ 0x7F) << (" ".length() << (" ".length() << " ".length()));
        en.lIIII[105] = 0xC3 ^ 0x92;
        en.lIIII[106] = (0x5E ^ 0x67) << " ".length();
        en.lIIII[107] = (0x91 ^ 0xB8) << " ".length();
        en.lIIII[108] = 0x41 ^ 0x12;
        en.lIIII[109] = (0x84 ^ 0xAF) << " ".length();
        en.lIIII[110] = 8 ^ 0x5F;
        en.lIIII[111] = (6 ^ 0xD) << "   ".length();
        en.lIIII[112] = 0xCD ^ 0x94;
        en.lIIII[113] = (0xEF ^ 0xC2) << " ".length();
        en.lIIII[114] = 0xC1 ^ 0x9A;
        en.lIIII[115] = (0x4E ^ 0x59) << (" ".length() << " ".length());
        en.lIIII[116] = 0x21 ^ 0x7C;
        en.lIIII[117] = -(0x64 ^ 0x3F);
        en.lIIII[118] = (0x21 ^ 0xE) << " ".length();
        en.lIIII[119] = 0xC7 ^ 0x98;
        en.lIIII[120] = "   ".length() << (0x43 ^ 0x46);
        en.lIIII[121] = (0x15 ^ 0x24) << " ".length();
        en.lIIII[122] = (0x54 ^ 0x67) << " ".length();
        en.lIIII[123] = (4 ^ 0x31) << " ".length();
        en.lIIII[124] = (0x63 ^ 0x78) << (" ".length() << " ".length());
        en.lIIII[125] = 0x2E ^ 0x43;
        en.lIIII[126] = 89239 + 456527 - 214318 + 668551;
        en.lIIII[127] = 0x10 ^ 0x61;
        en.lIIII[128] = -(0x24 ^ 0xB);
        en.lIIII[129] = -(0xF1 ^ 0xAE);
        en.lIIII[130] = -(0xDC ^ 0x8C);
        en.lIIII[131] = -(0x6B ^ 0x22);
        en.lIIII[132] = -(0x6D ^ 0x61);
    }
}

