/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.microedition.lcdui.Alert
 *  javax.microedition.lcdui.AlertType
 *  javax.microedition.lcdui.ChoiceGroup
 *  javax.microedition.lcdui.Command
 *  javax.microedition.lcdui.CommandListener
 *  javax.microedition.lcdui.Display
 *  javax.microedition.lcdui.Displayable
 *  javax.microedition.lcdui.Form
 *  javax.microedition.lcdui.Item
 *  javax.microedition.lcdui.ItemStateListener
 *  javax.microedition.midlet.MIDlet
 */
import javax.microedition.lcdui.Alert;
import javax.microedition.lcdui.AlertType;
import javax.microedition.lcdui.ChoiceGroup;
import javax.microedition.lcdui.Command;
import javax.microedition.lcdui.CommandListener;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import javax.microedition.lcdui.Form;
import javax.microedition.lcdui.Item;
import javax.microedition.lcdui.ItemStateListener;
import javax.microedition.midlet.MIDlet;

public class fk
extends Form
implements CommandListener,
ItemStateListener {
    private /* synthetic */ ChoiceGroup a;
    private /* synthetic */ ChoiceGroup b;
    private /* synthetic */ ChoiceGroup c;
    private /* synthetic */ Command d;
    private static final /* synthetic */ int[] llIl;

    public fk() {
        fk llllllIlllIlIll;
        byte[] byArray = new byte[llIl[0]];
        byArray[fk.llIl[1]] = llIl[1];
        byArray[fk.llIl[2]] = llIl[3];
        byArray[fk.llIl[4]] = llIl[1];
        byArray[fk.llIl[5]] = llIl[6];
        byArray[fk.llIl[7]] = llIl[1];
        byArray[fk.llIl[8]] = llIl[9];
        byArray[fk.llIl[10]] = llIl[1];
        byArray[fk.llIl[11]] = llIl[12];
        byArray[fk.llIl[13]] = llIl[2];
        byArray[fk.llIl[14]] = llIl[15];
        byArray[fk.llIl[16]] = llIl[17];
        byArray[fk.llIl[18]] = llIl[19];
        byArray[fk.llIl[20]] = llIl[1];
        byArray[fk.llIl[21]] = llIl[22];
        byArray[fk.llIl[23]] = llIl[1];
        byArray[fk.llIl[24]] = llIl[12];
        byArray[fk.llIl[25]] = llIl[1];
        byArray[fk.llIl[15]] = llIl[26];
        byArray[fk.llIl[27]] = llIl[1];
        byArray[fk.llIl[28]] = llIl[29];
        byArray[fk.llIl[30]] = llIl[1];
        byArray[fk.llIl[31]] = llIl[22];
        byArray[fk.llIl[32]] = llIl[1];
        byArray[fk.llIl[33]] = llIl[34];
        byArray[fk.llIl[35]] = llIl[1];
        byArray[fk.llIl[36]] = llIl[12];
        byArray[fk.llIl[37]] = llIl[1];
        byArray[fk.llIl[38]] = llIl[39];
        byArray[fk.llIl[40]] = llIl[1];
        byArray[fk.llIl[41]] = llIl[42];
        byArray[fk.llIl[17]] = llIl[1];
        byArray[fk.llIl[43]] = llIl[39];
        byArray[fk.llIl[12]] = llIl[1];
        byArray[fk.llIl[44]] = llIl[45];
        byArray[fk.llIl[46]] = llIl[1];
        byArray[fk.llIl[47]] = llIl[12];
        byArray[fk.llIl[48]] = llIl[1];
        byArray[fk.llIl[49]] = llIl[50];
        byArray[fk.llIl[51]] = llIl[17];
        byArray[fk.llIl[52]] = llIl[53];
        byArray[fk.llIl[54]] = llIl[1];
        byArray[fk.llIl[55]] = llIl[56];
        super(ec.a(byArray));
        byte[] byArray2 = new byte[llIl[40]];
        byArray2[fk.llIl[1]] = llIl[1];
        byArray2[fk.llIl[2]] = llIl[57];
        byArray2[fk.llIl[4]] = llIl[17];
        byArray2[fk.llIl[5]] = llIl[58];
        byArray2[fk.llIl[7]] = llIl[1];
        byArray2[fk.llIl[8]] = llIl[22];
        byArray2[fk.llIl[10]] = llIl[1];
        byArray2[fk.llIl[11]] = llIl[12];
        byArray2[fk.llIl[13]] = llIl[1];
        byArray2[fk.llIl[14]] = llIl[59];
        byArray2[fk.llIl[16]] = llIl[1];
        byArray2[fk.llIl[18]] = llIl[12];
        byArray2[fk.llIl[20]] = llIl[1];
        byArray2[fk.llIl[21]] = llIl[60];
        byArray2[fk.llIl[23]] = llIl[17];
        byArray2[fk.llIl[24]] = llIl[61];
        byArray2[fk.llIl[25]] = llIl[1];
        byArray2[fk.llIl[15]] = llIl[22];
        byArray2[fk.llIl[27]] = llIl[1];
        byArray2[fk.llIl[28]] = llIl[12];
        byArray2[fk.llIl[30]] = llIl[1];
        byArray2[fk.llIl[31]] = llIl[62];
        byArray2[fk.llIl[32]] = llIl[1];
        byArray2[fk.llIl[33]] = llIl[29];
        byArray2[fk.llIl[35]] = llIl[1];
        byArray2[fk.llIl[36]] = llIl[22];
        byArray2[fk.llIl[37]] = llIl[1];
        byArray2[fk.llIl[38]] = llIl[34];
        String[] stringArray = new String[llIl[4]];
        byte[] byArray3 = new byte[llIl[10]];
        byArray3[fk.llIl[1]] = llIl[1];
        byArray3[fk.llIl[2]] = llIl[57];
        byArray3[fk.llIl[4]] = llIl[17];
        byArray3[fk.llIl[5]] = llIl[58];
        byArray3[fk.llIl[7]] = llIl[1];
        byArray3[fk.llIl[8]] = llIl[22];
        stringArray[fk.llIl[1]] = ec.a(byArray3);
        byte[] byArray4 = new byte[llIl[10]];
        byArray4[fk.llIl[1]] = llIl[1];
        byArray4[fk.llIl[2]] = llIl[60];
        byArray4[fk.llIl[4]] = llIl[17];
        byArray4[fk.llIl[5]] = llIl[61];
        byArray4[fk.llIl[7]] = llIl[1];
        byArray4[fk.llIl[8]] = llIl[22];
        stringArray[fk.llIl[2]] = ec.a(byArray4);
        this.a = new ChoiceGroup(ec.a(byArray2), llIl[2], stringArray, null);
        this.append((Item)this.a);
        byte[] byArray5 = new byte[llIl[35]];
        byArray5[fk.llIl[1]] = llIl[1];
        byArray5[fk.llIl[2]] = llIl[63];
        byArray5[fk.llIl[4]] = llIl[1];
        byArray5[fk.llIl[5]] = llIl[26];
        byArray5[fk.llIl[7]] = llIl[1];
        byArray5[fk.llIl[8]] = llIl[64];
        byArray5[fk.llIl[10]] = llIl[1];
        byArray5[fk.llIl[11]] = llIl[12];
        byArray5[fk.llIl[13]] = llIl[1];
        byArray5[fk.llIl[14]] = llIl[39];
        byArray5[fk.llIl[16]] = llIl[1];
        byArray5[fk.llIl[18]] = llIl[42];
        byArray5[fk.llIl[20]] = llIl[1];
        byArray5[fk.llIl[21]] = llIl[39];
        byArray5[fk.llIl[23]] = llIl[1];
        byArray5[fk.llIl[24]] = llIl[45];
        byArray5[fk.llIl[25]] = llIl[1];
        byArray5[fk.llIl[15]] = llIl[12];
        byArray5[fk.llIl[27]] = llIl[1];
        byArray5[fk.llIl[28]] = llIl[50];
        byArray5[fk.llIl[30]] = llIl[17];
        byArray5[fk.llIl[31]] = llIl[53];
        byArray5[fk.llIl[32]] = llIl[1];
        byArray5[fk.llIl[33]] = llIl[56];
        String[] stringArray2 = new String[llIl[21]];
        byte[] byArray6 = new byte[llIl[7]];
        byArray6[fk.llIl[1]] = llIl[1];
        byArray6[fk.llIl[2]] = llIl[65];
        byArray6[fk.llIl[4]] = llIl[1];
        byArray6[fk.llIl[5]] = llIl[66];
        stringArray2[fk.llIl[1]] = ec.a(byArray6);
        byte[] byArray7 = new byte[llIl[7]];
        byArray7[fk.llIl[1]] = llIl[1];
        byArray7[fk.llIl[2]] = llIl[65];
        byArray7[fk.llIl[4]] = llIl[1];
        byArray7[fk.llIl[5]] = llIl[67];
        stringArray2[fk.llIl[2]] = ec.a(byArray7);
        byte[] byArray8 = new byte[llIl[7]];
        byArray8[fk.llIl[1]] = llIl[1];
        byArray8[fk.llIl[2]] = llIl[65];
        byArray8[fk.llIl[4]] = llIl[1];
        byArray8[fk.llIl[5]] = llIl[68];
        stringArray2[fk.llIl[4]] = ec.a(byArray8);
        byte[] byArray9 = new byte[llIl[7]];
        byArray9[fk.llIl[1]] = llIl[1];
        byArray9[fk.llIl[2]] = llIl[65];
        byArray9[fk.llIl[4]] = llIl[1];
        byArray9[fk.llIl[5]] = llIl[69];
        stringArray2[fk.llIl[5]] = ec.a(byArray9);
        byte[] byArray10 = new byte[llIl[7]];
        byArray10[fk.llIl[1]] = llIl[1];
        byArray10[fk.llIl[2]] = llIl[65];
        byArray10[fk.llIl[4]] = llIl[1];
        byArray10[fk.llIl[5]] = llIl[70];
        stringArray2[fk.llIl[7]] = ec.a(byArray10);
        byte[] byArray11 = new byte[llIl[7]];
        byArray11[fk.llIl[1]] = llIl[1];
        byArray11[fk.llIl[2]] = llIl[65];
        byArray11[fk.llIl[4]] = llIl[1];
        byArray11[fk.llIl[5]] = llIl[71];
        stringArray2[fk.llIl[8]] = ec.a(byArray11);
        byte[] byArray12 = new byte[llIl[10]];
        byArray12[fk.llIl[1]] = llIl[1];
        byArray12[fk.llIl[2]] = llIl[65];
        byArray12[fk.llIl[4]] = llIl[1];
        byArray12[fk.llIl[5]] = llIl[72];
        byArray12[fk.llIl[7]] = llIl[1];
        byArray12[fk.llIl[8]] = llIl[73];
        stringArray2[fk.llIl[10]] = ec.a(byArray12);
        byte[] byArray13 = new byte[llIl[10]];
        byArray13[fk.llIl[1]] = llIl[1];
        byArray13[fk.llIl[2]] = llIl[65];
        byArray13[fk.llIl[4]] = llIl[1];
        byArray13[fk.llIl[5]] = llIl[72];
        byArray13[fk.llIl[7]] = llIl[1];
        byArray13[fk.llIl[8]] = llIl[72];
        stringArray2[fk.llIl[11]] = ec.a(byArray13);
        byte[] byArray14 = new byte[llIl[10]];
        byArray14[fk.llIl[1]] = llIl[1];
        byArray14[fk.llIl[2]] = llIl[65];
        byArray14[fk.llIl[4]] = llIl[1];
        byArray14[fk.llIl[5]] = llIl[72];
        byArray14[fk.llIl[7]] = llIl[1];
        byArray14[fk.llIl[8]] = llIl[74];
        stringArray2[fk.llIl[13]] = ec.a(byArray14);
        byte[] byArray15 = new byte[llIl[10]];
        byArray15[fk.llIl[1]] = llIl[1];
        byArray15[fk.llIl[2]] = llIl[65];
        byArray15[fk.llIl[4]] = llIl[1];
        byArray15[fk.llIl[5]] = llIl[72];
        byArray15[fk.llIl[7]] = llIl[1];
        byArray15[fk.llIl[8]] = llIl[75];
        stringArray2[fk.llIl[14]] = ec.a(byArray15);
        byte[] byArray16 = new byte[llIl[10]];
        byArray16[fk.llIl[1]] = llIl[1];
        byArray16[fk.llIl[2]] = llIl[65];
        byArray16[fk.llIl[4]] = llIl[1];
        byArray16[fk.llIl[5]] = llIl[72];
        byArray16[fk.llIl[7]] = llIl[1];
        byArray16[fk.llIl[8]] = llIl[66];
        stringArray2[fk.llIl[16]] = ec.a(byArray16);
        byte[] byArray17 = new byte[llIl[10]];
        byArray17[fk.llIl[1]] = llIl[1];
        byArray17[fk.llIl[2]] = llIl[65];
        byArray17[fk.llIl[4]] = llIl[1];
        byArray17[fk.llIl[5]] = llIl[72];
        byArray17[fk.llIl[7]] = llIl[1];
        byArray17[fk.llIl[8]] = llIl[67];
        stringArray2[fk.llIl[18]] = ec.a(byArray17);
        byte[] byArray18 = new byte[llIl[10]];
        byArray18[fk.llIl[1]] = llIl[1];
        byArray18[fk.llIl[2]] = llIl[65];
        byArray18[fk.llIl[4]] = llIl[1];
        byArray18[fk.llIl[5]] = llIl[72];
        byArray18[fk.llIl[7]] = llIl[1];
        byArray18[fk.llIl[8]] = llIl[68];
        stringArray2[fk.llIl[20]] = ec.a(byArray18);
        this.b = new ChoiceGroup(ec.a(byArray5), llIl[2], stringArray2, null);
        this.append((Item)this.b);
        byte[] byArray19 = new byte[llIl[51]];
        byArray19[fk.llIl[1]] = llIl[1];
        byArray19[fk.llIl[2]] = llIl[76];
        byArray19[fk.llIl[4]] = llIl[1];
        byArray19[fk.llIl[5]] = llIl[42];
        byArray19[fk.llIl[7]] = llIl[1];
        byArray19[fk.llIl[8]] = llIl[39];
        byArray19[fk.llIl[10]] = llIl[1];
        byArray19[fk.llIl[11]] = llIl[45];
        byArray19[fk.llIl[13]] = llIl[1];
        byArray19[fk.llIl[14]] = llIl[12];
        byArray19[fk.llIl[16]] = llIl[1];
        byArray19[fk.llIl[18]] = llIl[50];
        byArray19[fk.llIl[20]] = llIl[17];
        byArray19[fk.llIl[21]] = llIl[53];
        byArray19[fk.llIl[23]] = llIl[1];
        byArray19[fk.llIl[24]] = llIl[56];
        byArray19[fk.llIl[25]] = llIl[1];
        byArray19[fk.llIl[15]] = llIl[12];
        byArray19[fk.llIl[27]] = llIl[1];
        byArray19[fk.llIl[28]] = llIl[65];
        byArray19[fk.llIl[30]] = llIl[1];
        byArray19[fk.llIl[31]] = llIl[70];
        byArray19[fk.llIl[32]] = llIl[1];
        byArray19[fk.llIl[33]] = llIl[12];
        byArray19[fk.llIl[35]] = llIl[1];
        byArray19[fk.llIl[36]] = llIl[77];
        byArray19[fk.llIl[37]] = llIl[1];
        byArray19[fk.llIl[38]] = llIl[78];
        byArray19[fk.llIl[40]] = llIl[1];
        byArray19[fk.llIl[41]] = llIl[39];
        byArray19[fk.llIl[17]] = llIl[1];
        byArray19[fk.llIl[43]] = llIl[45];
        byArray19[fk.llIl[12]] = llIl[1];
        byArray19[fk.llIl[44]] = llIl[12];
        byArray19[fk.llIl[46]] = llIl[2];
        byArray19[fk.llIl[47]] = llIl[15];
        byArray19[fk.llIl[48]] = llIl[1];
        byArray19[fk.llIl[49]] = llIl[79];
        String[] stringArray3 = new String[llIl[4]];
        byte[] byArray20 = new byte[llIl[13]];
        byArray20[fk.llIl[1]] = llIl[2];
        byArray20[fk.llIl[2]] = llIl[25];
        byArray20[fk.llIl[4]] = llIl[1];
        byArray20[fk.llIl[5]] = llIl[79];
        byArray20[fk.llIl[7]] = llIl[1];
        byArray20[fk.llIl[8]] = llIl[12];
        byArray20[fk.llIl[10]] = llIl[1];
        byArray20[fk.llIl[11]] = llIl[68];
        stringArray3[fk.llIl[1]] = ec.a(byArray20);
        byte[] byArray21 = new byte[llIl[13]];
        byArray21[fk.llIl[1]] = llIl[2];
        byArray21[fk.llIl[2]] = llIl[25];
        byArray21[fk.llIl[4]] = llIl[1];
        byArray21[fk.llIl[5]] = llIl[79];
        byArray21[fk.llIl[7]] = llIl[1];
        byArray21[fk.llIl[8]] = llIl[12];
        byArray21[fk.llIl[10]] = llIl[1];
        byArray21[fk.llIl[11]] = llIl[69];
        stringArray3[fk.llIl[2]] = ec.a(byArray21);
        this.c = new ChoiceGroup(ec.a(byArray19), llIl[2], stringArray3, null);
        if (at.U >= llIl[13]) {
            this.append((Item)this.c);
        }
        byte[] byArray22 = new byte[llIl[13]];
        byArray22[fk.llIl[1]] = llIl[1];
        byArray22[fk.llIl[2]] = llIl[80];
        byArray22[fk.llIl[4]] = llIl[1];
        byArray22[fk.llIl[5]] = llIl[26];
        byArray22[fk.llIl[7]] = llIl[1];
        byArray22[fk.llIl[8]] = llIl[81];
        byArray22[fk.llIl[10]] = llIl[1];
        byArray22[fk.llIl[11]] = llIl[82];
        llllllIlllIlIll.d = new Command(ec.a(byArray22), llIl[7], llIl[1]);
        llllllIlllIlIll.addCommand(llllllIlllIlIll.d);
        byte[] byArray23 = new byte[llIl[20]];
        byArray23[fk.llIl[1]] = llIl[1];
        byArray23[fk.llIl[2]] = llIl[3];
        byArray23[fk.llIl[4]] = llIl[1];
        byArray23[fk.llIl[5]] = llIl[26];
        byArray23[fk.llIl[7]] = llIl[1];
        byArray23[fk.llIl[8]] = llIl[39];
        byArray23[fk.llIl[10]] = llIl[1];
        byArray23[fk.llIl[11]] = llIl[50];
        byArray23[fk.llIl[13]] = llIl[1];
        byArray23[fk.llIl[14]] = llIl[82];
        byArray23[fk.llIl[16]] = llIl[1];
        byArray23[fk.llIl[18]] = llIl[83];
        llllllIlllIlIll.addCommand(new Command(ec.a(byArray23), llIl[11], llIl[2]));
        llllllIlllIlIll.setCommandListener(llllllIlllIlIll);
        llllllIlllIlIll.setItemStateListener(llllllIlllIlIll);
        llllllIlllIlIll.a.setSelectedIndex(at.T ? llIl[1] : llIl[2], llIl[2]);
        llllllIlllIlIll.b.setSelectedIndex(at.U - llIl[7], llIl[2]);
        llllllIlllIlIll.c.setSelectedIndex(at.W == llIl[10] ? llIl[2] : llIl[1], llIl[2]);
    }

    public final void commandAction(Command command, Displayable displayable) {
        if (command == this.d) {
            try {
                fk llllllIlllIIlll;
                at.T = llllllIlllIIlll.a.isSelected(llIl[1]);
                at.U = llllllIlllIIlll.b.getSelectedIndex() + llIl[7];
                at.W = llllllIlllIIlll.c.isSelected(llIl[2]) ? llIl[10] : llIl[8];
                byte[] byArray = new byte[llIl[84]];
                byArray[fk.llIl[1]] = llIl[1];
                byArray[fk.llIl[2]] = llIl[85];
                byArray[fk.llIl[4]] = llIl[2];
                byArray[fk.llIl[5]] = llIl[86];
                byArray[fk.llIl[7]] = llIl[1];
                byArray[fk.llIl[8]] = llIl[29];
                byArray[fk.llIl[10]] = llIl[1];
                byArray[fk.llIl[11]] = llIl[12];
                byArray[fk.llIl[13]] = llIl[1];
                byArray[fk.llIl[14]] = llIl[50];
                byArray[fk.llIl[16]] = llIl[1];
                byArray[fk.llIl[18]] = llIl[6];
                byArray[fk.llIl[20]] = llIl[1];
                byArray[fk.llIl[21]] = llIl[9];
                byArray[fk.llIl[23]] = llIl[1];
                byArray[fk.llIl[24]] = llIl[12];
                byArray[fk.llIl[25]] = llIl[2];
                byArray[fk.llIl[15]] = llIl[15];
                byArray[fk.llIl[27]] = llIl[17];
                byArray[fk.llIl[28]] = llIl[19];
                byArray[fk.llIl[30]] = llIl[1];
                byArray[fk.llIl[31]] = llIl[22];
                byArray[fk.llIl[32]] = llIl[1];
                byArray[fk.llIl[33]] = llIl[12];
                byArray[fk.llIl[35]] = llIl[1];
                byArray[fk.llIl[36]] = llIl[22];
                byArray[fk.llIl[37]] = llIl[1];
                byArray[fk.llIl[38]] = llIl[87];
                byArray[fk.llIl[40]] = llIl[1];
                byArray[fk.llIl[41]] = llIl[6];
                byArray[fk.llIl[17]] = llIl[1];
                byArray[fk.llIl[43]] = llIl[39];
                byArray[fk.llIl[12]] = llIl[1];
                byArray[fk.llIl[44]] = llIl[87];
                byArray[fk.llIl[46]] = llIl[1];
                byArray[fk.llIl[47]] = llIl[12];
                byArray[fk.llIl[48]] = llIl[1];
                byArray[fk.llIl[49]] = llIl[50];
                byArray[fk.llIl[51]] = llIl[1];
                byArray[fk.llIl[52]] = llIl[88];
                byArray[fk.llIl[54]] = llIl[1];
                byArray[fk.llIl[55]] = llIl[39];
                byArray[fk.llIl[0]] = llIl[1];
                byArray[fk.llIl[65]] = llIl[45];
                at.a(ec.a(byArray));
            }
            catch (Exception llllllIlllIIlIl) {
                byte[] byArray = new byte[llIl[10]];
                byArray[fk.llIl[1]] = llIl[1];
                byArray[fk.llIl[2]] = llIl[85];
                byArray[fk.llIl[4]] = llIl[17];
                byArray[fk.llIl[5]] = llIl[89];
                byArray[fk.llIl[7]] = llIl[1];
                byArray[fk.llIl[8]] = llIl[9];
                byte[] byArray2 = new byte[llIl[90]];
                byArray2[fk.llIl[1]] = llIl[1];
                byArray2[fk.llIl[2]] = llIl[3];
                byArray2[fk.llIl[4]] = llIl[1];
                byArray2[fk.llIl[5]] = llIl[91];
                byArray2[fk.llIl[7]] = llIl[1];
                byArray2[fk.llIl[8]] = llIl[12];
                byArray2[fk.llIl[10]] = llIl[1];
                byArray2[fk.llIl[11]] = llIl[83];
                byArray2[fk.llIl[13]] = llIl[17];
                byArray2[fk.llIl[14]] = llIl[89];
                byArray2[fk.llIl[16]] = llIl[1];
                byArray2[fk.llIl[18]] = llIl[9];
                byArray2[fk.llIl[20]] = llIl[1];
                byArray2[fk.llIl[21]] = llIl[12];
                byArray2[fk.llIl[23]] = llIl[1];
                byArray2[fk.llIl[24]] = llIl[64];
                byArray2[fk.llIl[25]] = llIl[17];
                byArray2[fk.llIl[15]] = llIl[92];
                byArray2[fk.llIl[27]] = llIl[1];
                byArray2[fk.llIl[28]] = llIl[93];
                byArray2[fk.llIl[30]] = llIl[1];
                byArray2[fk.llIl[31]] = llIl[12];
                byArray2[fk.llIl[32]] = llIl[1];
                byArray2[fk.llIl[33]] = llIl[94];
                byArray2[fk.llIl[35]] = llIl[1];
                byArray2[fk.llIl[36]] = llIl[26];
                byArray2[fk.llIl[37]] = llIl[1];
                byArray2[fk.llIl[38]] = llIl[95];
                byArray2[fk.llIl[40]] = llIl[1];
                byArray2[fk.llIl[41]] = llIl[12];
                byArray2[fk.llIl[17]] = llIl[1];
                byArray2[fk.llIl[43]] = llIl[96];
                byArray2[fk.llIl[12]] = llIl[1];
                byArray2[fk.llIl[44]] = llIl[97];
                byArray2[fk.llIl[46]] = llIl[1];
                byArray2[fk.llIl[47]] = llIl[93];
                byArray2[fk.llIl[48]] = llIl[1];
                byArray2[fk.llIl[49]] = llIl[12];
                byArray2[fk.llIl[51]] = llIl[1];
                byArray2[fk.llIl[52]] = llIl[64];
                byArray2[fk.llIl[54]] = llIl[1];
                byArray2[fk.llIl[55]] = llIl[82];
                byArray2[fk.llIl[0]] = llIl[1];
                byArray2[fk.llIl[65]] = llIl[98];
                byArray2[fk.llIl[84]] = llIl[1];
                byArray2[fk.llIl[99]] = llIl[12];
                byArray2[fk.llIl[95]] = llIl[1];
                byArray2[fk.llIl[59]] = llIl[83];
                byArray2[fk.llIl[73]] = llIl[17];
                byArray2[fk.llIl[72]] = llIl[100];
                byArray2[fk.llIl[74]] = llIl[1];
                byArray2[fk.llIl[75]] = llIl[9];
                byArray2[fk.llIl[66]] = llIl[1];
                byArray2[fk.llIl[67]] = llIl[12];
                byArray2[fk.llIl[68]] = llIl[1];
                byArray2[fk.llIl[69]] = llIl[50];
                byArray2[fk.llIl[70]] = llIl[1];
                byArray2[fk.llIl[71]] = llIl[6];
                byArray2[fk.llIl[101]] = llIl[1];
                byArray2[fk.llIl[102]] = llIl[9];
                byArray2[fk.llIl[103]] = llIl[1];
                byArray2[fk.llIl[104]] = llIl[12];
                byArray2[fk.llIl[105]] = llIl[2];
                byArray2[fk.llIl[106]] = llIl[15];
                byArray2[fk.llIl[107]] = llIl[17];
                byArray2[fk.llIl[62]] = llIl[19];
                byArray2[fk.llIl[57]] = llIl[1];
                byArray2[fk.llIl[3]] = llIl[22];
                byArray2[fk.llIl[108]] = llIl[1];
                byArray2[fk.llIl[109]] = llIl[44];
                Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)new Alert(ec.a(byArray), ec.a(byArray2), null, AlertType.ERROR));
                return;
            }
        }
        Display.getDisplay((MIDlet)bs.d).setCurrent((Displayable)dc.a);
    }

    public final void itemStateChanged(Item item) {
        if (item == this.b) {
            fk llllllIlllIIIlI;
            if (this.b.getSelectedIndex() >= llIl[7]) {
                if (this.size() < llIl[5]) {
                    this.append((Item)this.c);
                    return;
                }
            } else if (llllllIlllIIIlI.size() >= llIl[5] && llllllIlllIIIlI.get(llIl[4]) == llllllIlllIIIlI.c) {
                llllllIlllIIIlI.delete(llIl[4]);
            }
        }
    }

    static {
        fk.llIl();
    }

    private static void llIl() {
        llIl = new int[110];
        fk.llIl[0] = (0x70 ^ 0x65) << " ".length();
        fk.llIl[1] = (9 ^ 0x10) & ~(0x13 ^ 0xA);
        fk.llIl[2] = " ".length();
        fk.llIl[3] = 0x2D ^ 0x6E;
        fk.llIl[4] = " ".length() << " ".length();
        fk.llIl[5] = "   ".length();
        fk.llIl[6] = -(0xE0 ^ 0xC0);
        fk.llIl[7] = " ".length() << (" ".length() << " ".length());
        fk.llIl[8] = 0x7D ^ 0x78;
        fk.llIl[9] = 0x7F ^ 0x16;
        fk.llIl[10] = "   ".length() << " ".length();
        fk.llIl[11] = 0x84 ^ 0x83;
        fk.llIl[12] = " ".length() << (0x12 ^ 0x17);
        fk.llIl[13] = " ".length() << "   ".length();
        fk.llIl[14] = 0x3D ^ 0x34;
        fk.llIl[15] = 0x85 ^ 0x94;
        fk.llIl[16] = (0x20 ^ 0x25) << " ".length();
        fk.llIl[17] = (0xAC ^ 0xA3) << " ".length();
        fk.llIl[18] = 0xC9 ^ 0xC2;
        fk.llIl[19] = -(5 ^ 0x4C);
        fk.llIl[20] = "   ".length() << (" ".length() << " ".length());
        fk.llIl[21] = 0x6A ^ 0x67;
        fk.llIl[22] = (0x5F ^ 0x42) << (" ".length() << " ".length());
        fk.llIl[23] = (0xA2 ^ 0xA5) << " ".length();
        fk.llIl[24] = 0x59 ^ 0x56;
        fk.llIl[25] = " ".length() << (" ".length() << (" ".length() << " ".length()));
        fk.llIl[26] = 0x19 ^ 0x78;
        fk.llIl[27] = (0x66 ^ 0x6F) << " ".length();
        fk.llIl[28] = 0x8E ^ 0x9D;
        fk.llIl[29] = 0xA ^ 0x7F;
        fk.llIl[30] = (0x29 ^ 0x2C) << (" ".length() << " ".length());
        fk.llIl[31] = 0x1D ^ 8;
        fk.llIl[32] = (0x52 ^ 0x59) << " ".length();
        fk.llIl[33] = 0x72 ^ 0x65;
        fk.llIl[34] = 0x47 ^ 0x28;
        fk.llIl[35] = "   ".length() << "   ".length();
        fk.llIl[36] = 0xDF ^ 0xC6;
        fk.llIl[37] = (6 ^ 0xB) << " ".length();
        fk.llIl[38] = 0x4C ^ 0x57;
        fk.llIl[39] = (0x38 ^ 0xF) << " ".length();
        fk.llIl[40] = (0x95 ^ 0x92) << (" ".length() << " ".length());
        fk.llIl[41] = 0x37 ^ 0x2A;
        fk.llIl[42] = -(0x3B ^ 0x25);
        fk.llIl[43] = 0x45 ^ 0x5A;
        fk.llIl[44] = 0x27 ^ 6;
        fk.llIl[45] = 0xC3 ^ 0xA4;
        fk.llIl[46] = (0x38 ^ 0x29) << " ".length();
        fk.llIl[47] = 0xB6 ^ 0x95;
        fk.llIl[48] = (0x67 ^ 0x6E) << (" ".length() << " ".length());
        fk.llIl[49] = 0x35 ^ 0x10;
        fk.llIl[50] = 0xF2 ^ 0x91;
        fk.llIl[51] = (0x1A ^ 9) << " ".length();
        fk.llIl[52] = 0xC ^ 0x2B;
        fk.llIl[53] = -(0x9B ^ 0xC0);
        fk.llIl[54] = (0xBB ^ 0xBE) << "   ".length();
        fk.llIl[55] = 0xB ^ 0x22;
        fk.llIl[56] = (1 ^ 6) << (" ".length() << (" ".length() << " ".length()));
        fk.llIl[57] = (0x28 ^ 9) << " ".length();
        fk.llIl[58] = -(0 ^ 0x53);
        fk.llIl[59] = 0x7C ^ 0x53;
        fk.llIl[60] = (0x86 ^ 0x93) << (" ".length() << " ".length());
        fk.llIl[61] = -(0x31 ^ 0x60);
        fk.llIl[62] = 0x25 ^ 0x64;
        fk.llIl[63] = 0x41 ^ 0xC;
        fk.llIl[64] = (0x68 ^ 0x67) << "   ".length();
        fk.llIl[65] = 0x9E ^ 0xB5;
        fk.llIl[66] = (0x1D ^ 0x10) << (" ".length() << " ".length());
        fk.llIl[67] = 0x42 ^ 0x77;
        fk.llIl[68] = (0x61 ^ 0x7A) << " ".length();
        fk.llIl[69] = 4 ^ 0x33;
        fk.llIl[70] = (0xA7 ^ 0xA0) << "   ".length();
        fk.llIl[71] = 0x5F ^ 0x66;
        fk.llIl[72] = 0x87 ^ 0xB6;
        fk.llIl[73] = "   ".length() << (" ".length() << (" ".length() << " ".length()));
        fk.llIl[74] = (0xB3 ^ 0xAA) << " ".length();
        fk.llIl[75] = 0x68 ^ 0x5B;
        fk.llIl[76] = (0x42 ^ 0x65) << " ".length();
        fk.llIl[77] = (0xA7 ^ 0xBE) << (" ".length() << " ".length());
        fk.llIl[78] = -(0x44 ^ 0x43);
        fk.llIl[79] = -(0x52 ^ 0x4D);
        fk.llIl[80] = 0x36 ^ 0x65;
        fk.llIl[81] = (0x21 ^ 0x1A) << " ".length();
        fk.llIl[82] = 8 ^ 0x6D;
        fk.llIl[83] = (0x31 ^ 0x2A) << (" ".length() << " ".length());
        fk.llIl[84] = (0x52 ^ 0x59) << (" ".length() << " ".length());
        fk.llIl[85] = (0x8E ^ 0x9D) << (" ".length() << " ".length());
        fk.llIl[86] = -(0x13 ^ 0x43);
        fk.llIl[87] = (0x15 ^ 0x18) << "   ".length();
        fk.llIl[88] = -(0xBD ^ 0xB1);
        fk.llIl[89] = -(0x40 ^ 0x69);
        fk.llIl[90] = (0x26 ^ 5) << " ".length();
        fk.llIl[91] = -(0x7B ^ 0x76);
        fk.llIl[92] = -(0x4E ^ 0x13);
        fk.llIl[93] = 0x1A ^ 0x63;
        fk.llIl[94] = (0x1B ^ 0x22) << " ".length();
        fk.llIl[95] = (0x79 ^ 0x6E) << " ".length();
        fk.llIl[96] = (0x28 ^ 0x21) << "   ".length();
        fk.llIl[97] = -(0xAD ^ 0xB0);
        fk.llIl[98] = 0x15 ^ 0x78;
        fk.llIl[99] = 0xBE ^ 0x93;
        fk.llIl[100] = -(0x47 ^ 0x18);
        fk.llIl[101] = (0xE ^ 0x13) << " ".length();
        fk.llIl[102] = 0x8B ^ 0xB0;
        fk.llIl[103] = (0x35 ^ 0x3A) << (" ".length() << " ".length());
        fk.llIl[104] = 0x50 ^ 0x6D;
        fk.llIl[105] = (0xAC ^ 0xB3) << " ".length();
        fk.llIl[106] = 0xBA ^ 0x85;
        fk.llIl[107] = " ".length() << ("   ".length() << " ".length());
        fk.llIl[108] = (0x9E ^ 0x8F) << (" ".length() << " ".length());
        fk.llIl[109] = 1 ^ 0x44;
    }
}

